var searchData=
[
  ['cómo_20completar_0',['cómo completar',['../md_EXERCISES__ADVANCED.html#autotoc_md69',1,'Cómo Completar'],['../md_EXERCISES__INTERMEDIATE.html#autotoc_md121',1,'Cómo Completar']]],
  ['cómo_20completar_20los_20ejercicios_1',['Cómo Completar Los Ejercicios',['../md_EXERCISES__BEGINNER.html#autotoc_md94',1,'']]],
  ['cómo_20trabajar_20con_20estos_20proyectos_2',['🎓 Cómo Trabajar con Estos Proyectos',['../md_PROJECTS.html#autotoc_md178',1,'']]],
  ['cómo_20usar_20ahora_3',['Cómo usar ahora',['../md_DOCS__CHANGELOG.html#autotoc_md43',1,'']]],
  ['c_4',['c',['../md_CPP__STACK.html#autotoc_md14',1,'Catch2 (C++)'],['../md_CPP__STACK.html#autotoc_md17',1,'Librerías estándar de C']]],
  ['c_20c_20development_20stack_20—_20herramientas_20librerías_20y_20extensiones_20profesionales_5',['C/C++ Development Stack — Herramientas, librerías y extensiones profesionales',['../md_CPP__STACK.html',1,'']]],
  ['c_20construcción_20real_6',['Proyectos de C - Construcción Real',['../md_PROJECTS.html',1,'']]],
  ['c_20estándar_20stl_7',['Librerías C++ estándar (STL)',['../md_CPP__STACK.html#autotoc_md18',1,'']]],
  ['c_20nivel_20avanzado_8',['Ejercicios de C - Nivel Avanzado',['../md_EXERCISES__ADVANCED.html',1,'']]],
  ['c_20nivel_20intermedio_9',['Ejercicios de C - Nivel Intermedio',['../md_EXERCISES__INTERMEDIATE.html',1,'']]],
  ['c_20nivel_20principiante_10',['Ejercicios de C - Nivel Principiante',['../md_EXERCISES__BEGINNER.html',1,'']]],
  ['c_20o_20c_20con_20wrapper_11',['GoogleTest (C++ o C con wrapper)',['../md_CPP__STACK.html#autotoc_md15',1,'']]],
  ['c_20tt_20tt_20include_20math_5futils_20h_20tt_12',['4. Reusable Code (&lt;tt&gt;src/math_utils.c&lt;/tt&gt; + &lt;tt&gt;include/math_utils.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md221',1,'']]],
  ['c_20workplace_13',['Cambios y registro de documentación — c-workplace',['../md_DOCS__CHANGELOG.html',1,'']]],
  ['c_20workspace_20c_20workplace_14',['C Workspace (c-workplace)',['../md_README.html',1,'']]],
  ['c_20workspace_20worklog_15',['C Workspace Worklog',['../md_WORKLOG.html',1,'']]],
  ['c_3a_20vs_20code_20remote_20wsl_20recommended_16',['Option C: VS Code Remote - WSL (Recommended)',['../md_WORKLOG.html#autotoc_md234',1,'']]],
  ['cada_20cambio_17',['Descripción detallada de cada cambio',['../md_DOCS__CHANGELOG.html#autotoc_md42',1,'']]],
  ['cada_20proyecto_3a_18',['Para Cada Proyecto:',['../md_PROJECTS.html#autotoc_md179',1,'']]],
  ['calcula_20el_20absoluto_19',['Ejercicio 5: Función que Calcula el Absoluto',['../md_EXERCISES__BEGINNER.html#autotoc_md82',1,'']]],
  ['calcula_20potencia_20',['Ejercicio 7: Función que Calcula Potencia',['../md_EXERCISES__BEGINNER.html#autotoc_md86',1,'']]],
  ['calculadora_20interactiva_21',['Proyecto 1: Calculadora Interactiva',['../md_PROJECTS.html#autotoc_md156',1,'']]],
  ['cambio_22',['Descripción detallada de cada cambio',['../md_DOCS__CHANGELOG.html#autotoc_md42',1,'']]],
  ['cambios_20y_20registro_20de_20documentación_20—_20c_20workplace_23',['Cambios y registro de documentación — c-workplace',['../md_DOCS__CHANGELOG.html',1,'']]],
  ['can_20take_24',['Next Steps You Can Take',['../md_WORKLOG.html#autotoc_md238',1,'']]],
  ['catch2_20c_25',['Catch2 (C++)',['../md_CPP__STACK.html#autotoc_md14',1,'']]],
  ['cd_26',['CI/CD',['../md_CPP__STACK.html#autotoc_md33',1,'']]],
  ['check_20available_20tools_27',['Step 3: Check Available Tools',['../md_WORKLOG.html#autotoc_md194',1,'']]],
  ['ci_20cd_28',['CI/CD',['../md_CPP__STACK.html#autotoc_md33',1,'']]],
  ['clang_20format_29',['clang-format',['../md_CPP__STACK.html#autotoc_md30',1,'']]],
  ['clang_20llvm_30',['Clang (LLVM)',['../md_CPP__STACK.html#autotoc_md5',1,'']]],
  ['clangd_20análisis_20estático_20en_20ide_31',['Clangd (Análisis estático en IDE)',['../md_CPP__STACK.html#autotoc_md24',1,'']]],
  ['clean_20build_20artifacts_20optional_32',['Step 7: Clean Build Artifacts (Optional)',['../md_WORKLOG.html#autotoc_md198',1,'']]],
  ['clock_20skew_20detected_20warning_33',['&quot;Clock skew detected&quot; warning',['../md_WORKLOG.html#autotoc_md213',1,'']]],
  ['cmake_20profesional_34',['CMake (profesional)',['../md_CPP__STACK.html#autotoc_md9',1,'']]],
  ['cmd_35',['Option A: From Windows PowerShell/CMD',['../md_WORKLOG.html#autotoc_md232',1,'']]],
  ['code_36',['code',['../md_WORKLOG.html#autotoc_md203',1,'Build from VS Code'],['../md_WORKLOG.html#autotoc_md204',1,'Debug from VS Code'],['../md_CPP__STACK.html#autotoc_md28',1,'Extensiones de VS Code'],['../md_WORKLOG.html#autotoc_md205',1,'Terminal in VS Code']]],
  ['code_20extensions_20local_20wsl_37',['VS Code Extensions (Local + WSL)',['../md_WORKLOG.html#autotoc_md230',1,'']]],
  ['code_20integration_38',['6. VS Code Integration',['../md_WORKLOG.html#autotoc_md223',1,'']]],
  ['code_20remote_20wsl_20recommended_39',['code remote wsl recommended',['../md_WORKLOG.html#autotoc_md234',1,'Option C: VS Code Remote - WSL (Recommended)'],['../md_WORKLOG.html#autotoc_md201',1,'Using VS Code Remote - WSL (Recommended)']]],
  ['code_20tt_20src_20math_5futils_20c_20tt_20tt_20include_20math_5futils_20h_20tt_40',['4. Reusable Code (&lt;tt&gt;src/math_utils.c&lt;/tt&gt; + &lt;tt&gt;include/math_utils.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md221',1,'']]],
  ['cola_20queue_41',['Ejercicio 5: Cola (Queue)',['../md_EXERCISES__ADVANCED.html#autotoc_md57',1,'']]],
  ['collection_42',['GCC (GNU Compiler Collection)',['../md_CPP__STACK.html#autotoc_md4',1,'']]],
  ['comando_20rápido_20copiar_20y_20pegar_43',['Comando Rápido (Copiar y Pegar)',['../md_GITHUB__SETUP.html#autotoc_md141',1,'']]],
  ['comandos_20útiles_44',['Comandos Útiles',['../md_EXERCISES__BEGINNER.html#autotoc_md96',1,'']]],
  ['command_20not_20found_45',['command not found',['../md_WORKLOG.html#autotoc_md212',1,'&quot;gcc: command not found&quot;'],['../md_WORKLOG.html#autotoc_md211',1,'&quot;make: command not found&quot;']]],
  ['commands_20you_20have_20available_46',['Commands You Have Available',['../md_WORKLOG.html#autotoc_md244',1,'']]],
  ['commits_47',['Paso 4: Futuros Commits',['../md_GITHUB__SETUP.html#autotoc_md139',1,'']]],
  ['comparación_48',['comparación',['../md_CPP__STACK.html#autotoc_md10',1,'Comparación'],['../md_CPP__STACK.html#autotoc_md6',1,'Comparación']]],
  ['compilador_20integrado_49',['AddressSanitizer (Compilador integrado)',['../md_CPP__STACK.html#autotoc_md23',1,'']]],
  ['compilador_20minimalista_50',['Proyecto 7: Compilador Minimalista',['../md_PROJECTS.html#autotoc_md170',1,'']]],
  ['compiladores_20y_20toolchains_51',['Compiladores y toolchains',['../md_CPP__STACK.html#autotoc_md3',1,'']]],
  ['compiler_20collection_52',['GCC (GNU Compiler Collection)',['../md_CPP__STACK.html#autotoc_md4',1,'']]],
  ['completar_53',['completar',['../md_EXERCISES__ADVANCED.html#autotoc_md69',1,'Cómo Completar'],['../md_EXERCISES__INTERMEDIATE.html#autotoc_md121',1,'Cómo Completar']]],
  ['completar_20los_20ejercicios_54',['Cómo Completar Los Ejercicios',['../md_EXERCISES__BEGINNER.html#autotoc_md94',1,'']]],
  ['comprueba_20si_20es_20par_55',['Ejercicio 6: Función que Comprueba si es Par',['../md_EXERCISES__BEGINNER.html#autotoc_md84',1,'']]],
  ['con_20estos_20proyectos_56',['🎓 Cómo Trabajar con Estos Proyectos',['../md_PROJECTS.html#autotoc_md178',1,'']]],
  ['con_20https_57',['Alternativa: Token de Acceso (si falla con HTTPS)',['../md_GITHUB__SETUP.html#autotoc_md143',1,'']]],
  ['con_20struct_58',['Ejercicio 5: Función con Struct',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md109',1,'']]],
  ['con_20wrapper_59',['GoogleTest (C++ o C con wrapper)',['../md_CPP__STACK.html#autotoc_md15',1,'']]],
  ['conectar_20repositorio_20local_20a_20github_60',['Paso 2: Conectar Repositorio Local a GitHub',['../md_GITHUB__SETUP.html#autotoc_md135',1,'']]],
  ['configuración_20de_20git_61',['Verificar Configuración de Git',['../md_GITHUB__SETUP.html#autotoc_md145',1,'']]],
  ['configurations_20tt_20f5_20tt_62',['Debug Configurations (&lt;tt&gt;F5&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md225',1,'']]],
  ['construcción_20real_63',['Proyectos de C - Construcción Real',['../md_PROJECTS.html',1,'']]],
  ['contactos_64',['Proyecto 2: Gestor de Contactos',['../md_PROJECTS.html#autotoc_md158',1,'']]],
  ['contar_20ocurrencias_65',['Ejercicio 4: Contar Ocurrencias',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md107',1,'']]],
  ['copiar_20y_20pegar_66',['Comando Rápido (Copiar y Pegar)',['../md_GITHUB__SETUP.html#autotoc_md141',1,'']]],
  ['cpp_5fstack_2emd_67',['CPP_STACK.md',['../CPP__STACK_8md.html',1,'']]],
  ['cpplint_68',['cpplint',['../md_CPP__STACK.html#autotoc_md31',1,'']]],
  ['crear_20repositorio_20en_20github_69',['Paso 1: Crear Repositorio en GitHub',['../md_GITHUB__SETUP.html#autotoc_md133',1,'']]],
  ['created_20modified_70',['Files Created/Modified',['../md_WORKLOG.html#autotoc_md242',1,'']]],
  ['ctrl_20shift_20b_20tt_71',['Tasks (&lt;tt&gt;Ctrl+Shift+B&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md224',1,'']]],
  ['cuenta_20dígitos_72',['Ejercicio 4: Función que Cuenta Dígitos',['../md_EXERCISES__BEGINNER.html#autotoc_md80',1,'']]],
  ['cunit_73',['CUnit',['../md_CPP__STACK.html#autotoc_md13',1,'']]]
];
