var searchData=
[
  ['f5_20tt_0',['Debug Configurations (&lt;tt&gt;F5&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md225',1,'']]],
  ['factorial_1',['Ejercicio 1: Recursión - Factorial',['../md_EXERCISES__ADVANCED.html#autotoc_md49',1,'']]],
  ['falla_2',['Si Algo Falla',['../md_GITHUB__SETUP.html#autotoc_md147',1,'']]],
  ['falla_20con_20https_3',['Alternativa: Token de Acceso (si falla con HTTPS)',['../md_GITHUB__SETUP.html#autotoc_md143',1,'']]],
  ['fibonacci_4',['Ejercicio 2: Recursión - Fibonacci',['../md_EXERCISES__ADVANCED.html#autotoc_md51',1,'']]],
  ['files_20created_20modified_5',['Files Created/Modified',['../md_WORKLOG.html#autotoc_md242',1,'']]],
  ['filtrar_20array_6',['Ejercicio 7: Filtrar Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md113',1,'']]],
  ['flawfinder_20seguridad_7',['flawfinder (seguridad)',['../md_CPP__STACK.html#autotoc_md32',1,'']]],
  ['flujo_8',['Resumen del flujo',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md125',1,'']]],
  ['format_9',['clang-format',['../md_CPP__STACK.html#autotoc_md30',1,'']]],
  ['formateo_20y_20linting_10',['Formateo y linting',['../md_CPP__STACK.html#autotoc_md29',1,'']]],
  ['found_11',['found',['../md_WORKLOG.html#autotoc_md212',1,'&quot;gcc: command not found&quot;'],['../md_WORKLOG.html#autotoc_md211',1,'&quot;make: command not found&quot;']]],
  ['framework_20tt_20include_20test_20h_20tt_12',['3. Test Framework (&lt;tt&gt;include/test.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md220',1,'']]],
  ['frameworks_13',['Testing frameworks',['../md_CPP__STACK.html#autotoc_md11',1,'']]],
  ['from_20vs_20code_14',['from vs code',['../md_WORKLOG.html#autotoc_md203',1,'Build from VS Code'],['../md_WORKLOG.html#autotoc_md204',1,'Debug from VS Code']]],
  ['from_20windows_20powershell_20cmd_15',['Option A: From Windows PowerShell/CMD',['../md_WORKLOG.html#autotoc_md232',1,'']]],
  ['función_20con_20struct_16',['Ejercicio 5: Función con Struct',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md109',1,'']]],
  ['función_20de_20multiplicación_17',['Ejercicio 3: Función de Multiplicación',['../md_EXERCISES__BEGINNER.html#autotoc_md78',1,'']]],
  ['función_20de_20resta_18',['Ejercicio 2: Función de Resta',['../md_EXERCISES__BEGINNER.html#autotoc_md76',1,'']]],
  ['función_20de_20suma_20simple_19',['Ejercicio 1: Función de Suma Simple',['../md_EXERCISES__BEGINNER.html#autotoc_md74',1,'']]],
  ['función_20que_20calcula_20el_20absoluto_20',['Ejercicio 5: Función que Calcula el Absoluto',['../md_EXERCISES__BEGINNER.html#autotoc_md82',1,'']]],
  ['función_20que_20calcula_20potencia_21',['Ejercicio 7: Función que Calcula Potencia',['../md_EXERCISES__BEGINNER.html#autotoc_md86',1,'']]],
  ['función_20que_20comprueba_20si_20es_20par_22',['Ejercicio 6: Función que Comprueba si es Par',['../md_EXERCISES__BEGINNER.html#autotoc_md84',1,'']]],
  ['función_20que_20cuenta_20dígitos_23',['Ejercicio 4: Función que Cuenta Dígitos',['../md_EXERCISES__BEGINNER.html#autotoc_md80',1,'']]],
  ['función_20que_20encuentra_20el_20máximo_24',['Ejercicio 8: Función que Encuentra el Máximo',['../md_EXERCISES__BEGINNER.html#autotoc_md88',1,'']]],
  ['función_20que_20invierte_20un_20número_25',['Ejercicio 10: Función que Invierte un Número',['../md_EXERCISES__BEGINNER.html#autotoc_md92',1,'']]],
  ['función_20que_20suma_20tres_20números_26',['Ejercicio 9: Función que Suma Tres Números',['../md_EXERCISES__BEGINNER.html#autotoc_md90',1,'']]],
  ['function_27',['Scenario: Add a New Math Function',['../md_WORKLOG.html#autotoc_md208',1,'']]],
  ['futuros_20commits_28',['Paso 4: Futuros Commits',['../md_GITHUB__SETUP.html#autotoc_md139',1,'']]]
];
