var searchData=
[
  ['rápido_20copiar_20y_20pegar_0',['Comando Rápido (Copiar y Pegar)',['../md_GITHUB__SETUP.html#autotoc_md141',1,'']]],
  ['readme_2emd_1',['README.md',['../README_8md.html',1,'']]],
  ['real_2',['Proyectos de C - Construcción Real',['../md_PROJECTS.html',1,'']]],
  ['recomendadas_3',['Referencias y lecturas recomendadas',['../md_DOCS__CHANGELOG.html#autotoc_md45',1,'']]],
  ['recomendado_4',['Stack recomendado',['../md_CPP__STACK.html#autotoc_md2',1,'']]],
  ['recommended_5',['recommended',['../md_WORKLOG.html#autotoc_md234',1,'Option C: VS Code Remote - WSL (Recommended)'],['../md_WORKLOG.html#autotoc_md201',1,'Using VS Code Remote - WSL (Recommended)']]],
  ['recommended_20extensions_6',['Recommended Extensions',['../md_WORKLOG.html#autotoc_md226',1,'']]],
  ['recursión_20factorial_7',['Ejercicio 1: Recursión - Factorial',['../md_EXERCISES__ADVANCED.html#autotoc_md49',1,'']]],
  ['recursión_20fibonacci_8',['Ejercicio 2: Recursión - Fibonacci',['../md_EXERCISES__ADVANCED.html#autotoc_md51',1,'']]],
  ['recursivo_9',['Ejercicio 7: Quicksort Recursivo',['../md_EXERCISES__ADVANCED.html#autotoc_md61',1,'']]],
  ['recursos_20útiles_10',['Recursos útiles',['../md_CPP__STACK.html#autotoc_md39',1,'']]],
  ['recursos_20adicionales_11',['💡 Recursos Adicionales',['../md_PROJECTS.html#autotoc_md182',1,'']]],
  ['referencias_20y_20lecturas_20recomendadas_12',['Referencias y lecturas recomendadas',['../md_DOCS__CHANGELOG.html#autotoc_md45',1,'']]],
  ['registro_20de_20documentación_20—_20c_20workplace_13',['Cambios y registro de documentación — c-workplace',['../md_DOCS__CHANGELOG.html',1,'']]],
  ['reinas_20backtracking_14',['Ejercicio 10: Problema N-Reinas (Backtracking)',['../md_EXERCISES__ADVANCED.html#autotoc_md67',1,'']]],
  ['remote_20wsl_20recommended_15',['remote wsl recommended',['../md_WORKLOG.html#autotoc_md234',1,'Option C: VS Code Remote - WSL (Recommended)'],['../md_WORKLOG.html#autotoc_md201',1,'Using VS Code Remote - WSL (Recommended)']]],
  ['repositorio_20en_20github_16',['Paso 1: Crear Repositorio en GitHub',['../md_GITHUB__SETUP.html#autotoc_md133',1,'']]],
  ['repositorio_20local_20a_20github_17',['Paso 2: Conectar Repositorio Local a GitHub',['../md_GITHUB__SETUP.html#autotoc_md135',1,'']]],
  ['repository_18',['5. Git Repository',['../md_WORKLOG.html#autotoc_md222',1,'']]],
  ['requisitos_19',['Requisitos',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md126',1,'']]],
  ['resta_20',['Ejercicio 2: Función de Resta',['../md_EXERCISES__BEGINNER.html#autotoc_md76',1,'']]],
  ['resumen_21',['📋 Tabla Resumen',['../md_PROJECTS.html#autotoc_md176',1,'']]],
  ['resumen_20de_20acciones_22',['Resumen de acciones',['../md_DOCS__CHANGELOG.html#autotoc_md41',1,'']]],
  ['resumen_20del_20flujo_23',['Resumen del flujo',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md125',1,'']]],
  ['reusable_20code_20tt_20src_20math_5futils_20c_20tt_20tt_20include_20math_5futils_20h_20tt_24',['4. Reusable Code (&lt;tt&gt;src/math_utils.c&lt;/tt&gt; + &lt;tt&gt;include/math_utils.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md221',1,'']]],
  ['roadmap_25',['Learning Roadmap',['../learning_roadmap.html',1,'']]],
  ['run_20tests_26',['Step 6: Run Tests',['../md_WORKLOG.html#autotoc_md197',1,'']]],
  ['run_20the_20program_27',['Step 5: Run the Program',['../md_WORKLOG.html#autotoc_md196',1,'']]],
  ['running_20tt_20build_20main_20tt_28',['&quot;Permission denied&quot; when running &lt;tt&gt;build/main&lt;/tt&gt;',['../md_WORKLOG.html#autotoc_md215',1,'']]]
];
