var searchData=
[
  ['pages_0',['GitHub Actions — Publicar documentación Doxygen en GitHub Pages',['../md_GITHUB__ACTIONS__GUIDE.html',1,'']]],
  ['par_1',['Ejercicio 6: Función que Comprueba si es Par',['../md_EXERCISES__BEGINNER.html#autotoc_md44',1,'']]],
  ['para_20cada_20proyecto_3a_2',['Para Cada Proyecto:',['../md_PROJECTS.html#autotoc_md139',1,'']]],
  ['paso_3',['paso',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md83',1,'Próximo Paso'],['../md_EXERCISES__BEGINNER.html#autotoc_md58',1,'Próximo Paso']]],
  ['paso_201_3a_20crear_20repositorio_20en_20github_4',['Paso 1: Crear Repositorio en GitHub',['../md_GITHUB__SETUP.html#autotoc_md93',1,'']]],
  ['paso_202_3a_20conectar_20repositorio_20local_20a_20github_5',['Paso 2: Conectar Repositorio Local a GitHub',['../md_GITHUB__SETUP.html#autotoc_md95',1,'']]],
  ['paso_203_3a_20verificar_20que_20se_20subió_6',['Paso 3: Verificar que se Subió',['../md_GITHUB__SETUP.html#autotoc_md97',1,'']]],
  ['paso_204_3a_20futuros_20commits_7',['Paso 4: Futuros Commits',['../md_GITHUB__SETUP.html#autotoc_md99',1,'']]],
  ['pasos_8',['Próximos Pasos',['../md_EXERCISES__ADVANCED.html#autotoc_md31',1,'']]],
  ['pasos_20después_20de_20estos_20proyectos_9',['🏆 Próximos Pasos Después de Estos Proyectos',['../md_PROJECTS.html#autotoc_md144',1,'']]],
  ['pasos_20en_20github_10',['Próximos Pasos en GitHub',['../md_GITHUB__SETUP.html#autotoc_md111',1,'']]],
  ['pegar_11',['Comando Rápido (Copiar y Pegar)',['../md_GITHUB__SETUP.html#autotoc_md101',1,'']]],
  ['permisos_12',['Seguridad y permisos',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md89',1,'']]],
  ['permission_20denied_20when_20running_20tt_20build_20main_20tt_13',['&quot;Permission denied&quot; when running &lt;tt&gt;build/main&lt;/tt&gt;',['../md_WORKLOG.html#autotoc_md175',1,'']]],
  ['pila_20stack_14',['Ejercicio 4: Pila (Stack)',['../md_EXERCISES__ADVANCED.html#autotoc_md15',1,'']]],
  ['potencia_15',['Ejercicio 7: Función que Calcula Potencia',['../md_EXERCISES__BEGINNER.html#autotoc_md46',1,'']]],
  ['powershell_20cmd_16',['Option A: From Windows PowerShell/CMD',['../md_WORKLOG.html#autotoc_md192',1,'']]],
  ['próximo_20paso_17',['próximo paso',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md83',1,'Próximo Paso'],['../md_EXERCISES__BEGINNER.html#autotoc_md58',1,'Próximo Paso']]],
  ['próximos_20pasos_18',['Próximos Pasos',['../md_EXERCISES__ADVANCED.html#autotoc_md31',1,'']]],
  ['próximos_20pasos_20después_20de_20estos_20proyectos_19',['🏆 Próximos Pasos Después de Estos Proyectos',['../md_PROJECTS.html#autotoc_md144',1,'']]],
  ['próximos_20pasos_20en_20github_20',['Próximos Pasos en GitHub',['../md_GITHUB__SETUP.html#autotoc_md111',1,'']]],
  ['principiante_21',['principiante',['../md_PROJECTS.html#autotoc_md115',1,'🔰 NIVEL PRINCIPIANTE'],['../md_EXERCISES__BEGINNER.html',1,'Ejercicios de C - Nivel Principiante']]],
  ['problema_20n_20reinas_20backtracking_22',['Ejercicio 10: Problema N-Reinas (Backtracking)',['../md_EXERCISES__ADVANCED.html#autotoc_md27',1,'']]],
  ['profundidad_20dfs_23',['Ejercicio 9: Búsqueda en Profundidad (DFS)',['../md_EXERCISES__ADVANCED.html#autotoc_md25',1,'']]],
  ['program_24',['Step 5: Run the Program',['../md_WORKLOG.html#autotoc_md156',1,'']]],
  ['project_25',['project',['../md_WORKLOG.html#autotoc_md153',1,'Step 2: Navigate to Your Project'],['../md_WORKLOG.html#autotoc_md155',1,'Step 4: Build the Project']]],
  ['project_20structure_26',['1. Project Structure',['../md_WORKLOG.html#autotoc_md178',1,'']]],
  ['project_20summary_27',['Project Summary',['../md_WORKLOG.html#autotoc_md149',1,'']]],
  ['projects_2emd_28',['PROJECTS.md',['../PROJECTS_8md.html',1,'']]],
  ['proyecto_29',['Estado Actual de tu Proyecto',['../md_GITHUB__SETUP.html#autotoc_md109',1,'']]],
  ['proyecto_201_3a_20calculadora_20interactiva_30',['Proyecto 1: Calculadora Interactiva',['../md_PROJECTS.html#autotoc_md116',1,'']]],
  ['proyecto_202_3a_20gestor_20de_20contactos_31',['Proyecto 2: Gestor de Contactos',['../md_PROJECTS.html#autotoc_md118',1,'']]],
  ['proyecto_203_3a_20editor_20de_20texto_20minimalista_32',['Proyecto 3: Editor de Texto Minimalista',['../md_PROJECTS.html#autotoc_md120',1,'']]],
  ['proyecto_204_3a_20sistema_20de_20gestión_20de_20estudiantes_33',['Proyecto 4: Sistema de Gestión de Estudiantes',['../md_PROJECTS.html#autotoc_md123',1,'']]],
  ['proyecto_205_3a_20simulador_20de_20banco_34',['Proyecto 5: Simulador de Banco',['../md_PROJECTS.html#autotoc_md125',1,'']]],
  ['proyecto_206_3a_20analizador_20de_20logs_35',['Proyecto 6: Analizador de Logs',['../md_PROJECTS.html#autotoc_md127',1,'']]],
  ['proyecto_207_3a_20compilador_20minimalista_36',['Proyecto 7: Compilador Minimalista',['../md_PROJECTS.html#autotoc_md130',1,'']]],
  ['proyecto_208_3a_20base_20de_20datos_20simple_20b_20tree_37',['Proyecto 8: Base de Datos Simple (B-Tree)',['../md_PROJECTS.html#autotoc_md132',1,'']]],
  ['proyecto_209_3a_20máquina_20virtual_20simple_20vm_38',['Proyecto 9: Máquina Virtual Simple (VM)',['../md_PROJECTS.html#autotoc_md134',1,'']]],
  ['proyecto_3a_39',['Para Cada Proyecto:',['../md_PROJECTS.html#autotoc_md139',1,'']]],
  ['proyectos_40',['proyectos',['../md_PROJECTS.html#autotoc_md138',1,'🎓 Cómo Trabajar con Estos Proyectos'],['../md_PROJECTS.html#autotoc_md144',1,'🏆 Próximos Pasos Después de Estos Proyectos']]],
  ['proyectos_20de_20c_20construcción_20real_41',['Proyectos de C - Construcción Real',['../md_PROJECTS.html',1,'']]],
  ['publicar_20documentación_20doxygen_20en_20github_20pages_42',['GitHub Actions — Publicar documentación Doxygen en GitHub Pages',['../md_GITHUB__ACTIONS__GUIDE.html',1,'']]],
  ['push_43',['Qué esperar después del push',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md88',1,'']]]
];
