var searchData=
[
  ['rápido_20copiar_20y_20pegar_0',['Comando Rápido (Copiar y Pegar)',['../md_GITHUB__SETUP.html#autotoc_md101',1,'']]],
  ['readme_2emd_1',['README.md',['../README_8md.html',1,'']]],
  ['real_2',['Proyectos de C - Construcción Real',['../md_PROJECTS.html',1,'']]],
  ['recomendadas_3',['Referencias y lecturas recomendadas',['../md_DOCS__CHANGELOG.html#autotoc_md5',1,'']]],
  ['recommended_4',['recommended',['../md_WORKLOG.html#autotoc_md194',1,'Option C: VS Code Remote - WSL (Recommended)'],['../md_WORKLOG.html#autotoc_md161',1,'Using VS Code Remote - WSL (Recommended)']]],
  ['recommended_20extensions_5',['Recommended Extensions',['../md_WORKLOG.html#autotoc_md186',1,'']]],
  ['recursión_20factorial_6',['Ejercicio 1: Recursión - Factorial',['../md_EXERCISES__ADVANCED.html#autotoc_md9',1,'']]],
  ['recursión_20fibonacci_7',['Ejercicio 2: Recursión - Fibonacci',['../md_EXERCISES__ADVANCED.html#autotoc_md11',1,'']]],
  ['recursivo_8',['Ejercicio 7: Quicksort Recursivo',['../md_EXERCISES__ADVANCED.html#autotoc_md21',1,'']]],
  ['recursos_20adicionales_9',['💡 Recursos Adicionales',['../md_PROJECTS.html#autotoc_md142',1,'']]],
  ['referencias_20y_20lecturas_20recomendadas_10',['Referencias y lecturas recomendadas',['../md_DOCS__CHANGELOG.html#autotoc_md5',1,'']]],
  ['registro_20de_20documentación_20—_20c_20workplace_11',['Cambios y registro de documentación — c-workplace',['../md_DOCS__CHANGELOG.html',1,'']]],
  ['reinas_20backtracking_12',['Ejercicio 10: Problema N-Reinas (Backtracking)',['../md_EXERCISES__ADVANCED.html#autotoc_md27',1,'']]],
  ['remote_20wsl_20recommended_13',['remote wsl recommended',['../md_WORKLOG.html#autotoc_md194',1,'Option C: VS Code Remote - WSL (Recommended)'],['../md_WORKLOG.html#autotoc_md161',1,'Using VS Code Remote - WSL (Recommended)']]],
  ['repositorio_20en_20github_14',['Paso 1: Crear Repositorio en GitHub',['../md_GITHUB__SETUP.html#autotoc_md93',1,'']]],
  ['repositorio_20local_20a_20github_15',['Paso 2: Conectar Repositorio Local a GitHub',['../md_GITHUB__SETUP.html#autotoc_md95',1,'']]],
  ['repository_16',['5. Git Repository',['../md_WORKLOG.html#autotoc_md182',1,'']]],
  ['requisitos_17',['Requisitos',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md86',1,'']]],
  ['resta_18',['Ejercicio 2: Función de Resta',['../md_EXERCISES__BEGINNER.html#autotoc_md36',1,'']]],
  ['resumen_19',['📋 Tabla Resumen',['../md_PROJECTS.html#autotoc_md136',1,'']]],
  ['resumen_20de_20acciones_20',['Resumen de acciones',['../md_DOCS__CHANGELOG.html#autotoc_md1',1,'']]],
  ['resumen_20del_20flujo_21',['Resumen del flujo',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md85',1,'']]],
  ['reusable_20code_20tt_20src_20math_5futils_20c_20tt_20tt_20include_20math_5futils_20h_20tt_22',['4. Reusable Code (&lt;tt&gt;src/math_utils.c&lt;/tt&gt; + &lt;tt&gt;include/math_utils.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md181',1,'']]],
  ['run_20tests_23',['Step 6: Run Tests',['../md_WORKLOG.html#autotoc_md157',1,'']]],
  ['run_20the_20program_24',['Step 5: Run the Program',['../md_WORKLOG.html#autotoc_md156',1,'']]],
  ['running_20tt_20build_20main_20tt_25',['&quot;Permission denied&quot; when running &lt;tt&gt;build/main&lt;/tt&gt;',['../md_WORKLOG.html#autotoc_md175',1,'']]]
];
