var searchData=
[
  ['dígitos_0',['Ejercicio 4: Función que Cuenta Dígitos',['../md_EXERCISES__BEGINNER.html#autotoc_md40',1,'']]],
  ['datos_20simple_20b_20tree_1',['Proyecto 8: Base de Datos Simple (B-Tree)',['../md_PROJECTS.html#autotoc_md132',1,'']]],
  ['de_20acceso_20si_20falla_20con_20https_2',['Alternativa: Token de Acceso (si falla con HTTPS)',['../md_GITHUB__SETUP.html#autotoc_md103',1,'']]],
  ['de_20acciones_3',['Resumen de acciones',['../md_DOCS__CHANGELOG.html#autotoc_md1',1,'']]],
  ['de_20archivos_4',['Ejercicio 8: Manejo de Archivos',['../md_EXERCISES__ADVANCED.html#autotoc_md23',1,'']]],
  ['de_20array_5',['Ejercicio 10: Estadísticas de Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md79',1,'']]],
  ['de_20banco_6',['Proyecto 5: Simulador de Banco',['../md_PROJECTS.html#autotoc_md125',1,'']]],
  ['de_20c_20construcción_20real_7',['Proyectos de C - Construcción Real',['../md_PROJECTS.html',1,'']]],
  ['de_20c_20nivel_20avanzado_8',['Ejercicios de C - Nivel Avanzado',['../md_EXERCISES__ADVANCED.html',1,'']]],
  ['de_20c_20nivel_20intermedio_9',['Ejercicios de C - Nivel Intermedio',['../md_EXERCISES__INTERMEDIATE.html',1,'']]],
  ['de_20c_20nivel_20principiante_10',['Ejercicios de C - Nivel Principiante',['../md_EXERCISES__BEGINNER.html',1,'']]],
  ['de_20cada_20cambio_11',['Descripción detallada de cada cambio',['../md_DOCS__CHANGELOG.html#autotoc_md2',1,'']]],
  ['de_20contactos_12',['Proyecto 2: Gestor de Contactos',['../md_PROJECTS.html#autotoc_md118',1,'']]],
  ['de_20datos_20simple_20b_20tree_13',['Proyecto 8: Base de Datos Simple (B-Tree)',['../md_PROJECTS.html#autotoc_md132',1,'']]],
  ['de_20documentación_20—_20c_20workplace_14',['Cambios y registro de documentación — c-workplace',['../md_DOCS__CHANGELOG.html',1,'']]],
  ['de_20ejemplo_15',['Workflow de ejemplo',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md87',1,'']]],
  ['de_20estos_20proyectos_16',['🏆 Próximos Pasos Después de Estos Proyectos',['../md_PROJECTS.html#autotoc_md144',1,'']]],
  ['de_20gestión_20de_20estudiantes_17',['Proyecto 4: Sistema de Gestión de Estudiantes',['../md_PROJECTS.html#autotoc_md123',1,'']]],
  ['de_20git_18',['Verificar Configuración de Git',['../md_GITHUB__SETUP.html#autotoc_md105',1,'']]],
  ['de_20lista_20enlazada_19',['Ejercicio 3: Nodo de Lista Enlazada',['../md_EXERCISES__ADVANCED.html#autotoc_md13',1,'']]],
  ['de_20logs_20',['Proyecto 6: Analizador de Logs',['../md_PROJECTS.html#autotoc_md127',1,'']]],
  ['de_20multiplicación_21',['Ejercicio 3: Función de Multiplicación',['../md_EXERCISES__BEGINNER.html#autotoc_md38',1,'']]],
  ['de_20resta_22',['Ejercicio 2: Función de Resta',['../md_EXERCISES__BEGINNER.html#autotoc_md36',1,'']]],
  ['de_20suma_20simple_23',['Ejercicio 1: Función de Suma Simple',['../md_EXERCISES__BEGINNER.html#autotoc_md34',1,'']]],
  ['de_20texto_20minimalista_24',['Proyecto 3: Editor de Texto Minimalista',['../md_PROJECTS.html#autotoc_md120',1,'']]],
  ['de_20tu_20proyecto_25',['Estado Actual de tu Proyecto',['../md_GITHUB__SETUP.html#autotoc_md109',1,'']]],
  ['debug_20configurations_20tt_20f5_20tt_26',['Debug Configurations (&lt;tt&gt;F5&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md185',1,'']]],
  ['debug_20from_20vs_20code_27',['Debug from VS Code',['../md_WORKLOG.html#autotoc_md164',1,'']]],
  ['debugger_28',['Breakpoints not working in debugger',['../md_WORKLOG.html#autotoc_md174',1,'']]],
  ['debugging_3a_29',['Debugging:',['../md_PROJECTS.html#autotoc_md140',1,'']]],
  ['del_20flujo_30',['Resumen del flujo',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md85',1,'']]],
  ['del_20push_31',['Qué esperar después del push',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md88',1,'']]],
  ['denied_20when_20running_20tt_20build_20main_20tt_32',['&quot;Permission denied&quot; when running &lt;tt&gt;build/main&lt;/tt&gt;',['../md_WORKLOG.html#autotoc_md175',1,'']]],
  ['descripción_20detallada_20de_20cada_20cambio_33',['Descripción detallada de cada cambio',['../md_DOCS__CHANGELOG.html#autotoc_md2',1,'']]],
  ['después_20de_20estos_20proyectos_34',['🏆 Próximos Pasos Después de Estos Proyectos',['../md_PROJECTS.html#autotoc_md144',1,'']]],
  ['después_20del_20push_35',['Qué esperar después del push',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md88',1,'']]],
  ['detallada_20de_20cada_20cambio_36',['Descripción detallada de cada cambio',['../md_DOCS__CHANGELOG.html#autotoc_md2',1,'']]],
  ['detected_20warning_37',['&quot;Clock skew detected&quot; warning',['../md_WORKLOG.html#autotoc_md173',1,'']]],
  ['dfs_38',['Ejercicio 9: Búsqueda en Profundidad (DFS)',['../md_EXERCISES__ADVANCED.html#autotoc_md25',1,'']]],
  ['docs_5fchangelog_2emd_39',['DOCS_CHANGELOG.md',['../DOCS__CHANGELOG_8md.html',1,'']]],
  ['documentación_20—_20c_20workplace_40',['Cambios y registro de documentación — c-workplace',['../md_DOCS__CHANGELOG.html',1,'']]],
  ['documentación_20doxygen_20en_20github_20pages_41',['GitHub Actions — Publicar documentación Doxygen en GitHub Pages',['../md_GITHUB__ACTIONS__GUIDE.html',1,'']]],
  ['doxygen_20en_20github_20pages_42',['GitHub Actions — Publicar documentación Doxygen en GitHub Pages',['../md_GITHUB__ACTIONS__GUIDE.html',1,'']]],
  ['duplicar_20array_43',['Ejercicio 6: Duplicar Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md71',1,'']]]
];
