var searchData=
[
  ['dígitos_0',['Ejercicio 4: Función que Cuenta Dígitos',['../md_EXERCISES__BEGINNER.html#autotoc_md80',1,'']]],
  ['datos_20simple_20b_20tree_1',['Proyecto 8: Base de Datos Simple (B-Tree)',['../md_PROJECTS.html#autotoc_md172',1,'']]],
  ['de_20acceso_20si_20falla_20con_20https_2',['Alternativa: Token de Acceso (si falla con HTTPS)',['../md_GITHUB__SETUP.html#autotoc_md143',1,'']]],
  ['de_20acciones_3',['Resumen de acciones',['../md_DOCS__CHANGELOG.html#autotoc_md41',1,'']]],
  ['de_20análisis_20y_20debugging_4',['Herramientas de análisis y debugging',['../md_CPP__STACK.html#autotoc_md20',1,'']]],
  ['de_20archivos_5',['Ejercicio 8: Manejo de Archivos',['../md_EXERCISES__ADVANCED.html#autotoc_md63',1,'']]],
  ['de_20array_6',['Ejercicio 10: Estadísticas de Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md119',1,'']]],
  ['de_20banco_7',['Proyecto 5: Simulador de Banco',['../md_PROJECTS.html#autotoc_md165',1,'']]],
  ['de_20c_8',['Librerías estándar de C',['../md_CPP__STACK.html#autotoc_md17',1,'']]],
  ['de_20c_20construcción_20real_9',['Proyectos de C - Construcción Real',['../md_PROJECTS.html',1,'']]],
  ['de_20c_20nivel_20avanzado_10',['Ejercicios de C - Nivel Avanzado',['../md_EXERCISES__ADVANCED.html',1,'']]],
  ['de_20c_20nivel_20intermedio_11',['Ejercicios de C - Nivel Intermedio',['../md_EXERCISES__INTERMEDIATE.html',1,'']]],
  ['de_20c_20nivel_20principiante_12',['Ejercicios de C - Nivel Principiante',['../md_EXERCISES__BEGINNER.html',1,'']]],
  ['de_20cada_20cambio_13',['Descripción detallada de cada cambio',['../md_DOCS__CHANGELOG.html#autotoc_md42',1,'']]],
  ['de_20contactos_14',['Proyecto 2: Gestor de Contactos',['../md_PROJECTS.html#autotoc_md158',1,'']]],
  ['de_20datos_20simple_20b_20tree_15',['Proyecto 8: Base de Datos Simple (B-Tree)',['../md_PROJECTS.html#autotoc_md172',1,'']]],
  ['de_20documentación_20—_20c_20workplace_16',['Cambios y registro de documentación — c-workplace',['../md_DOCS__CHANGELOG.html',1,'']]],
  ['de_20ejemplo_17',['Workflow de ejemplo',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md127',1,'']]],
  ['de_20estos_20proyectos_18',['🏆 Próximos Pasos Después de Estos Proyectos',['../md_PROJECTS.html#autotoc_md184',1,'']]],
  ['de_20gestión_20de_20estudiantes_19',['Proyecto 4: Sistema de Gestión de Estudiantes',['../md_PROJECTS.html#autotoc_md163',1,'']]],
  ['de_20git_20',['Verificar Configuración de Git',['../md_GITHUB__SETUP.html#autotoc_md145',1,'']]],
  ['de_20lista_20enlazada_21',['Ejercicio 3: Nodo de Lista Enlazada',['../md_EXERCISES__ADVANCED.html#autotoc_md53',1,'']]],
  ['de_20logs_22',['Proyecto 6: Analizador de Logs',['../md_PROJECTS.html#autotoc_md167',1,'']]],
  ['de_20multiplicación_23',['Ejercicio 3: Función de Multiplicación',['../md_EXERCISES__BEGINNER.html#autotoc_md78',1,'']]],
  ['de_20resta_24',['Ejercicio 2: Función de Resta',['../md_EXERCISES__BEGINNER.html#autotoc_md76',1,'']]],
  ['de_20suma_20simple_25',['Ejercicio 1: Función de Suma Simple',['../md_EXERCISES__BEGINNER.html#autotoc_md74',1,'']]],
  ['de_20texto_20minimalista_26',['Proyecto 3: Editor de Texto Minimalista',['../md_PROJECTS.html#autotoc_md160',1,'']]],
  ['de_20tu_20proyecto_27',['Estado Actual de tu Proyecto',['../md_GITHUB__SETUP.html#autotoc_md149',1,'']]],
  ['de_20vs_20code_28',['Extensiones de VS Code',['../md_CPP__STACK.html#autotoc_md28',1,'']]],
  ['debug_20configurations_20tt_20f5_20tt_29',['Debug Configurations (&lt;tt&gt;F5&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md225',1,'']]],
  ['debug_20from_20vs_20code_30',['Debug from VS Code',['../md_WORKLOG.html#autotoc_md204',1,'']]],
  ['debugger_31',['debugger',['../md_WORKLOG.html#autotoc_md214',1,'Breakpoints not working in debugger'],['../md_CPP__STACK.html#autotoc_md21',1,'GDB (GNU Debugger)']]],
  ['debugging_32',['debugging',['../md_CPP__STACK.html#autotoc_md20',1,'Herramientas de análisis y debugging'],['../md_CPP__STACK.html#autotoc_md22',1,'Valgrind (Memory debugging)']]],
  ['debugging_3a_33',['Debugging:',['../md_PROJECTS.html#autotoc_md180',1,'']]],
  ['del_20flujo_34',['Resumen del flujo',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md125',1,'']]],
  ['del_20push_35',['Qué esperar después del push',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md128',1,'']]],
  ['denied_20when_20running_20tt_20build_20main_20tt_36',['&quot;Permission denied&quot; when running &lt;tt&gt;build/main&lt;/tt&gt;',['../md_WORKLOG.html#autotoc_md215',1,'']]],
  ['descripción_20detallada_20de_20cada_20cambio_37',['Descripción detallada de cada cambio',['../md_DOCS__CHANGELOG.html#autotoc_md42',1,'']]],
  ['después_20de_20estos_20proyectos_38',['🏆 Próximos Pasos Después de Estos Proyectos',['../md_PROJECTS.html#autotoc_md184',1,'']]],
  ['después_20del_20push_39',['Qué esperar después del push',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md128',1,'']]],
  ['detallada_20de_20cada_20cambio_40',['Descripción detallada de cada cambio',['../md_DOCS__CHANGELOG.html#autotoc_md42',1,'']]],
  ['detected_20warning_41',['&quot;Clock skew detected&quot; warning',['../md_WORKLOG.html#autotoc_md213',1,'']]],
  ['development_20stack_20—_20herramientas_20librerías_20y_20extensiones_20profesionales_42',['C/C++ Development Stack — Herramientas, librerías y extensiones profesionales',['../md_CPP__STACK.html',1,'']]],
  ['dfs_43',['Ejercicio 9: Búsqueda en Profundidad (DFS)',['../md_EXERCISES__ADVANCED.html#autotoc_md65',1,'']]],
  ['docs_5fchangelog_2emd_44',['DOCS_CHANGELOG.md',['../DOCS__CHANGELOG_8md.html',1,'']]],
  ['documentación_45',['Documentación',['../md_CPP__STACK.html#autotoc_md25',1,'']]],
  ['documentación_20—_20c_20workplace_46',['Cambios y registro de documentación — c-workplace',['../md_DOCS__CHANGELOG.html',1,'']]],
  ['documentación_20avanzada_47',['Sphinx (Documentación avanzada)',['../md_CPP__STACK.html#autotoc_md27',1,'']]],
  ['documentación_20doxygen_20en_20github_20pages_48',['GitHub Actions — Publicar documentación Doxygen en GitHub Pages',['../md_GITHUB__ACTIONS__GUIDE.html',1,'']]],
  ['doxygen_49',['Doxygen',['../md_CPP__STACK.html#autotoc_md26',1,'']]],
  ['doxygen_20en_20github_20pages_50',['GitHub Actions — Publicar documentación Doxygen en GitHub Pages',['../md_GITHUB__ACTIONS__GUIDE.html',1,'']]],
  ['duplicar_20array_51',['Ejercicio 6: Duplicar Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md111',1,'']]]
];
