var searchData=
[
  ['safety_20notes_0',['Safety Notes',['../md_WORKLOG.html#autotoc_md240',1,'']]],
  ['scenario_3a_20add_20a_20new_20math_20function_1',['Scenario: Add a New Math Function',['../md_WORKLOG.html#autotoc_md208',1,'']]],
  ['se_20subió_2',['Paso 3: Verificar que se Subió',['../md_GITHUB__SETUP.html#autotoc_md137',1,'']]],
  ['seguridad_3',['flawfinder (seguridad)',['../md_CPP__STACK.html#autotoc_md32',1,'']]],
  ['seguridad_20y_20permisos_4',['Seguridad y permisos',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md129',1,'']]],
  ['setup_5',['Setup',['../md_WORKLOG.html#autotoc_md202',1,'']]],
  ['shift_20b_20tt_6',['Tasks (&lt;tt&gt;Ctrl+Shift+B&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md224',1,'']]],
  ['si_20algo_20falla_7',['Si Algo Falla',['../md_GITHUB__SETUP.html#autotoc_md147',1,'']]],
  ['si_20es_20par_8',['Ejercicio 6: Función que Comprueba si es Par',['../md_EXERCISES__BEGINNER.html#autotoc_md84',1,'']]],
  ['si_20falla_20con_20https_9',['Alternativa: Token de Acceso (si falla con HTTPS)',['../md_GITHUB__SETUP.html#autotoc_md143',1,'']]],
  ['siguientes_20pasos_10',['Siguientes pasos',['../md_CPP__STACK.html#autotoc_md38',1,'']]],
  ['simple_11',['simple',['../md_EXERCISES__BEGINNER.html#autotoc_md74',1,'Ejercicio 1: Función de Suma Simple'],['../md_EXERCISES__ADVANCED.html#autotoc_md59',1,'Ejercicio 6: Árbol Binario Simple']]],
  ['simple_20b_20tree_12',['Proyecto 8: Base de Datos Simple (B-Tree)',['../md_PROJECTS.html#autotoc_md172',1,'']]],
  ['simple_20vm_13',['Proyecto 9: Máquina Virtual Simple (VM)',['../md_PROJECTS.html#autotoc_md174',1,'']]],
  ['simulador_20de_20banco_14',['Proyecto 5: Simulador de Banco',['../md_PROJECTS.html#autotoc_md165',1,'']]],
  ['sistema_20de_20gestión_20de_20estudiantes_15',['Proyecto 4: Sistema de Gestión de Estudiantes',['../md_PROJECTS.html#autotoc_md163',1,'']]],
  ['skew_20detected_20warning_16',['&quot;Clock skew detected&quot; warning',['../md_WORKLOG.html#autotoc_md213',1,'']]],
  ['sort_17',['Ejercicio 9: Bubble Sort',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md117',1,'']]],
  ['sphinx_20documentación_20avanzada_18',['Sphinx (Documentación avanzada)',['../md_CPP__STACK.html#autotoc_md27',1,'']]],
  ['src_20math_5futils_20c_20tt_20tt_20include_20math_5futils_20h_20tt_19',['4. Reusable Code (&lt;tt&gt;src/math_utils.c&lt;/tt&gt; + &lt;tt&gt;include/math_utils.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md221',1,'']]],
  ['stack_20',['stack',['../cpp_stack_guide.html',1,'C/C++ Development Stack'],['../md_EXERCISES__ADVANCED.html#autotoc_md55',1,'Ejercicio 4: Pila (Stack)']]],
  ['stack_20—_20herramientas_20librerías_20y_20extensiones_20profesionales_21',['C/C++ Development Stack — Herramientas, librerías y extensiones profesionales',['../md_CPP__STACK.html',1,'']]],
  ['stack_20minimalista_20vs_20profesional_22',['Stack minimalista vs profesional',['../md_CPP__STACK.html#autotoc_md35',1,'']]],
  ['stack_20recomendado_23',['Stack recomendado',['../md_CPP__STACK.html#autotoc_md2',1,'']]],
  ['started_20step_20by_20step_24',['Getting Started (Step-by-Step)',['../md_WORKLOG.html#autotoc_md191',1,'']]],
  ['step_201_3a_20launch_20wsl_25',['Step 1: Launch WSL',['../md_WORKLOG.html#autotoc_md192',1,'']]],
  ['step_202_3a_20navigate_20to_20your_20project_26',['Step 2: Navigate to Your Project',['../md_WORKLOG.html#autotoc_md193',1,'']]],
  ['step_203_3a_20check_20available_20tools_27',['Step 3: Check Available Tools',['../md_WORKLOG.html#autotoc_md194',1,'']]],
  ['step_204_3a_20build_20the_20project_28',['Step 4: Build the Project',['../md_WORKLOG.html#autotoc_md195',1,'']]],
  ['step_205_3a_20run_20the_20program_29',['Step 5: Run the Program',['../md_WORKLOG.html#autotoc_md196',1,'']]],
  ['step_206_3a_20run_20tests_30',['Step 6: Run Tests',['../md_WORKLOG.html#autotoc_md197',1,'']]],
  ['step_207_3a_20clean_20build_20artifacts_20optional_31',['Step 7: Clean Build Artifacts (Optional)',['../md_WORKLOG.html#autotoc_md198',1,'']]],
  ['step_208_3a_20use_20git_20optional_32',['Step 8: Use Git (Optional)',['../md_WORKLOG.html#autotoc_md199',1,'']]],
  ['step_20by_20step_33',['Getting Started (Step-by-Step)',['../md_WORKLOG.html#autotoc_md191',1,'']]],
  ['steps_20you_20can_20take_34',['Next Steps You Can Take',['../md_WORKLOG.html#autotoc_md238',1,'']]],
  ['stl_35',['Librerías C++ estándar (STL)',['../md_CPP__STACK.html#autotoc_md18',1,'']]],
  ['struct_36',['Ejercicio 5: Función con Struct',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md109',1,'']]],
  ['structure_37',['1. Project Structure',['../md_WORKLOG.html#autotoc_md218',1,'']]],
  ['subió_38',['Paso 3: Verificar que se Subió',['../md_GITHUB__SETUP.html#autotoc_md137',1,'']]],
  ['subir_20a_20github_39',['📤 Guía: Subir a GitHub',['../md_GITHUB__SETUP.html',1,'']]],
  ['suma_20simple_40',['Ejercicio 1: Función de Suma Simple',['../md_EXERCISES__BEGINNER.html#autotoc_md74',1,'']]],
  ['suma_20tres_20números_41',['Ejercicio 9: Función que Suma Tres Números',['../md_EXERCISES__BEGINNER.html#autotoc_md90',1,'']]],
  ['summary_42',['Project Summary',['../md_WORKLOG.html#autotoc_md189',1,'']]],
  ['system_20makefile_43',['2. Build System (Makefile)',['../md_WORKLOG.html#autotoc_md219',1,'']]],
  ['systems_44',['Build systems',['../md_CPP__STACK.html#autotoc_md7',1,'']]]
];
