var searchData=
[
  ['tabla_20resumen_0',['📋 Tabla Resumen',['../md_PROJECTS.html#autotoc_md176',1,'']]],
  ['take_1',['Next Steps You Can Take',['../md_WORKLOG.html#autotoc_md238',1,'']]],
  ['tasks_20tt_20ctrl_20shift_20b_20tt_2',['Tasks (&lt;tt&gt;Ctrl+Shift+B&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md224',1,'']]],
  ['terminal_3',['Option B: Open WSL Terminal',['../md_WORKLOG.html#autotoc_md233',1,'']]],
  ['terminal_20in_20vs_20code_4',['Terminal in VS Code',['../md_WORKLOG.html#autotoc_md205',1,'']]],
  ['test_20framework_20tt_20include_20test_20h_20tt_5',['3. Test Framework (&lt;tt&gt;include/test.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md220',1,'']]],
  ['test_20h_20tt_6',['3. Test Framework (&lt;tt&gt;include/test.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md220',1,'']]],
  ['test_2eh_7',['test.h',['../test_8h.html',1,'']]],
  ['test_5fsummary_8',['TEST_SUMMARY',['../test_8h.html#a66a58a37b34ef08e76b8700dca4fa9ca',1,'test.h']]],
  ['testing_20frameworks_9',['Testing frameworks',['../md_CPP__STACK.html#autotoc_md11',1,'']]],
  ['tests_10',['Step 6: Run Tests',['../md_WORKLOG.html#autotoc_md197',1,'']]],
  ['texto_20minimalista_11',['Proyecto 3: Editor de Texto Minimalista',['../md_PROJECTS.html#autotoc_md160',1,'']]],
  ['the_20program_12',['Step 5: Run the Program',['../md_WORKLOG.html#autotoc_md196',1,'']]],
  ['the_20project_13',['Step 4: Build the Project',['../md_WORKLOG.html#autotoc_md195',1,'']]],
  ['to_20access_20use_14',['How to Access &amp; Use',['../md_WORKLOG.html#autotoc_md231',1,'']]],
  ['to_20your_20project_15',['Step 2: Navigate to Your Project',['../md_WORKLOG.html#autotoc_md193',1,'']]],
  ['token_20de_20acceso_20si_20falla_20con_20https_16',['Alternativa: Token de Acceso (si falla con HTTPS)',['../md_GITHUB__SETUP.html#autotoc_md143',1,'']]],
  ['toolchains_17',['Compiladores y toolchains',['../md_CPP__STACK.html#autotoc_md3',1,'']]],
  ['tools_18',['Step 3: Check Available Tools',['../md_WORKLOG.html#autotoc_md194',1,'']]],
  ['tools_20environment_19',['Tools &amp; Environment',['../md_WORKLOG.html#autotoc_md228',1,'']]],
  ['trabajar_20con_20estos_20proyectos_20',['🎓 Cómo Trabajar con Estos Proyectos',['../md_PROJECTS.html#autotoc_md178',1,'']]],
  ['tree_21',['Proyecto 8: Base de Datos Simple (B-Tree)',['../md_PROJECTS.html#autotoc_md172',1,'']]],
  ['tres_20números_22',['Ejercicio 9: Función que Suma Tres Números',['../md_EXERCISES__BEGINNER.html#autotoc_md90',1,'']]],
  ['troubleshooting_23',['Troubleshooting',['../md_WORKLOG.html#autotoc_md210',1,'']]],
  ['tt_20build_20main_20tt_24',['&quot;Permission denied&quot; when running &lt;tt&gt;build/main&lt;/tt&gt;',['../md_WORKLOG.html#autotoc_md215',1,'']]],
  ['tt_20ctrl_20shift_20b_20tt_25',['Tasks (&lt;tt&gt;Ctrl+Shift+B&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md224',1,'']]],
  ['tt_20f5_20tt_26',['Debug Configurations (&lt;tt&gt;F5&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md225',1,'']]],
  ['tt_20include_20test_20h_20tt_27',['3. Test Framework (&lt;tt&gt;include/test.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md220',1,'']]],
  ['tt_20src_20math_5futils_20c_20tt_20tt_20include_20math_5futils_20h_20tt_28',['4. Reusable Code (&lt;tt&gt;src/math_utils.c&lt;/tt&gt; + &lt;tt&gt;include/math_utils.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md221',1,'']]],
  ['tu_20proyecto_29',['Estado Actual de tu Proyecto',['../md_GITHUB__SETUP.html#autotoc_md149',1,'']]],
  ['typical_20workflow_30',['Typical Workflow',['../md_WORKLOG.html#autotoc_md207',1,'']]]
];
