var searchData=
[
  ['a_20github_0',['a github',['../md_GITHUB__SETUP.html',1,'📤 Guía: Subir a GitHub'],['../md_GITHUB__SETUP.html#autotoc_md135',1,'Paso 2: Conectar Repositorio Local a GitHub']]],
  ['a_20new_20math_20function_1',['Scenario: Add a New Math Function',['../md_WORKLOG.html#autotoc_md208',1,'']]],
  ['a_3a_20from_20windows_20powershell_20cmd_2',['Option A: From Windows PowerShell/CMD',['../md_WORKLOG.html#autotoc_md232',1,'']]],
  ['absoluto_3',['Ejercicio 5: Función que Calcula el Absoluto',['../md_EXERCISES__BEGINNER.html#autotoc_md82',1,'']]],
  ['acceso_20si_20falla_20con_20https_4',['Alternativa: Token de Acceso (si falla con HTTPS)',['../md_GITHUB__SETUP.html#autotoc_md143',1,'']]],
  ['access_20use_5',['How to Access &amp; Use',['../md_WORKLOG.html#autotoc_md231',1,'']]],
  ['acciones_6',['Resumen de acciones',['../md_DOCS__CHANGELOG.html#autotoc_md41',1,'']]],
  ['actions_20—_20publicar_20documentación_20doxygen_20en_20github_20pages_7',['GitHub Actions — Publicar documentación Doxygen en GitHub Pages',['../md_GITHUB__ACTIONS__GUIDE.html',1,'']]],
  ['actions_20guide_8',['GitHub Actions Guide',['../github_actions_guide.html',1,'']]],
  ['actions_20workflow_9',['GitHub Actions workflow',['../md_CPP__STACK.html#autotoc_md34',1,'']]],
  ['actual_20de_20tu_20proyecto_10',['Estado Actual de tu Proyecto',['../md_GITHUB__SETUP.html#autotoc_md149',1,'']]],
  ['add_20a_20new_20math_20function_11',['Scenario: Add a New Math Function',['../md_WORKLOG.html#autotoc_md208',1,'']]],
  ['addresssanitizer_20compilador_20integrado_12',['AddressSanitizer (Compilador integrado)',['../md_CPP__STACK.html#autotoc_md23',1,'']]],
  ['adicionales_13',['💡 Recursos Adicionales',['../md_PROJECTS.html#autotoc_md182',1,'']]],
  ['ahora_14',['Cómo usar ahora',['../md_DOCS__CHANGELOG.html#autotoc_md43',1,'']]],
  ['algo_20falla_15',['Si Algo Falla',['../md_GITHUB__SETUP.html#autotoc_md147',1,'']]],
  ['alternativa_3a_20token_20de_20acceso_20si_20falla_20con_20https_16',['Alternativa: Token de Acceso (si falla con HTTPS)',['../md_GITHUB__SETUP.html#autotoc_md143',1,'']]],
  ['análisis_20estático_20en_20ide_17',['Clangd (Análisis estático en IDE)',['../md_CPP__STACK.html#autotoc_md24',1,'']]],
  ['análisis_20y_20debugging_18',['Herramientas de análisis y debugging',['../md_CPP__STACK.html#autotoc_md20',1,'']]],
  ['analizador_20de_20logs_19',['Proyecto 6: Analizador de Logs',['../md_PROJECTS.html#autotoc_md167',1,'']]],
  ['archivos_20',['Ejercicio 8: Manejo de Archivos',['../md_EXERCISES__ADVANCED.html#autotoc_md63',1,'']]],
  ['array_21',['array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md119',1,'Ejercicio 10: Estadísticas de Array'],['../md_EXERCISES__INTERMEDIATE.html#autotoc_md103',1,'Ejercicio 2: Encontrar el Máximo en un Array'],['../md_EXERCISES__INTERMEDIATE.html#autotoc_md105',1,'Ejercicio 3: Invertir un Array'],['../md_EXERCISES__INTERMEDIATE.html#autotoc_md111',1,'Ejercicio 6: Duplicar Array'],['../md_EXERCISES__INTERMEDIATE.html#autotoc_md113',1,'Ejercicio 7: Filtrar Array']]],
  ['arrays_20y_20bucles_22',['Ejercicio 1: Arrays y Bucles',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md101',1,'']]],
  ['artifacts_20optional_23',['Step 7: Clean Build Artifacts (Optional)',['../md_WORKLOG.html#autotoc_md198',1,'']]],
  ['assert_20integrado_24',['Assert (integrado)',['../md_CPP__STACK.html#autotoc_md12',1,'']]],
  ['assert_5feq_25',['ASSERT_EQ',['../test_8h.html#a69307cd91a0ecb364f35b426b65b9da4',1,'test.h']]],
  ['assert_5ftrue_26',['ASSERT_TRUE',['../test_8h.html#ae9244bfbda562e8b798789b001993fa5',1,'test.h']]],
  ['available_27',['Commands You Have Available',['../md_WORKLOG.html#autotoc_md244',1,'']]],
  ['available_20tools_28',['Step 3: Check Available Tools',['../md_WORKLOG.html#autotoc_md194',1,'']]],
  ['avanzada_29',['Sphinx (Documentación avanzada)',['../md_CPP__STACK.html#autotoc_md27',1,'']]],
  ['avanzado_30',['avanzado',['../md_PROJECTS.html#autotoc_md169',1,'🚀 NIVEL AVANZADO'],['../md_EXERCISES__ADVANCED.html',1,'Ejercicios de C - Nivel Avanzado']]]
];
