var searchData=
[
  ['tabla_20resumen_0',['📋 Tabla Resumen',['../md_PROJECTS.html#autotoc_md136',1,'']]],
  ['take_1',['Next Steps You Can Take',['../md_WORKLOG.html#autotoc_md198',1,'']]],
  ['tasks_20tt_20ctrl_20shift_20b_20tt_2',['Tasks (&lt;tt&gt;Ctrl+Shift+B&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md184',1,'']]],
  ['terminal_3',['Option B: Open WSL Terminal',['../md_WORKLOG.html#autotoc_md193',1,'']]],
  ['terminal_20in_20vs_20code_4',['Terminal in VS Code',['../md_WORKLOG.html#autotoc_md165',1,'']]],
  ['test_20framework_20tt_20include_20test_20h_20tt_5',['3. Test Framework (&lt;tt&gt;include/test.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md180',1,'']]],
  ['test_20h_20tt_6',['3. Test Framework (&lt;tt&gt;include/test.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md180',1,'']]],
  ['test_2eh_7',['test.h',['../test_8h.html',1,'']]],
  ['test_5fsummary_8',['TEST_SUMMARY',['../test_8h.html#a66a58a37b34ef08e76b8700dca4fa9ca',1,'test.h']]],
  ['tests_9',['Step 6: Run Tests',['../md_WORKLOG.html#autotoc_md157',1,'']]],
  ['texto_20minimalista_10',['Proyecto 3: Editor de Texto Minimalista',['../md_PROJECTS.html#autotoc_md120',1,'']]],
  ['the_20program_11',['Step 5: Run the Program',['../md_WORKLOG.html#autotoc_md156',1,'']]],
  ['the_20project_12',['Step 4: Build the Project',['../md_WORKLOG.html#autotoc_md155',1,'']]],
  ['to_20access_20use_13',['How to Access &amp; Use',['../md_WORKLOG.html#autotoc_md191',1,'']]],
  ['to_20your_20project_14',['Step 2: Navigate to Your Project',['../md_WORKLOG.html#autotoc_md153',1,'']]],
  ['token_20de_20acceso_20si_20falla_20con_20https_15',['Alternativa: Token de Acceso (si falla con HTTPS)',['../md_GITHUB__SETUP.html#autotoc_md103',1,'']]],
  ['tools_16',['Step 3: Check Available Tools',['../md_WORKLOG.html#autotoc_md154',1,'']]],
  ['tools_20environment_17',['Tools &amp; Environment',['../md_WORKLOG.html#autotoc_md188',1,'']]],
  ['trabajar_20con_20estos_20proyectos_18',['🎓 Cómo Trabajar con Estos Proyectos',['../md_PROJECTS.html#autotoc_md138',1,'']]],
  ['tree_19',['Proyecto 8: Base de Datos Simple (B-Tree)',['../md_PROJECTS.html#autotoc_md132',1,'']]],
  ['tres_20números_20',['Ejercicio 9: Función que Suma Tres Números',['../md_EXERCISES__BEGINNER.html#autotoc_md50',1,'']]],
  ['troubleshooting_21',['Troubleshooting',['../md_WORKLOG.html#autotoc_md170',1,'']]],
  ['tt_20build_20main_20tt_22',['&quot;Permission denied&quot; when running &lt;tt&gt;build/main&lt;/tt&gt;',['../md_WORKLOG.html#autotoc_md175',1,'']]],
  ['tt_20ctrl_20shift_20b_20tt_23',['Tasks (&lt;tt&gt;Ctrl+Shift+B&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md184',1,'']]],
  ['tt_20f5_20tt_24',['Debug Configurations (&lt;tt&gt;F5&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md185',1,'']]],
  ['tt_20include_20test_20h_20tt_25',['3. Test Framework (&lt;tt&gt;include/test.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md180',1,'']]],
  ['tt_20src_20math_5futils_20c_20tt_20tt_20include_20math_5futils_20h_20tt_26',['4. Reusable Code (&lt;tt&gt;src/math_utils.c&lt;/tt&gt; + &lt;tt&gt;include/math_utils.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md181',1,'']]],
  ['tu_20proyecto_27',['Estado Actual de tu Proyecto',['../md_GITHUB__SETUP.html#autotoc_md109',1,'']]],
  ['typical_20workflow_28',['Typical Workflow',['../md_WORKLOG.html#autotoc_md167',1,'']]]
];
