var searchData=
[
  ['safety_20notes_0',['Safety Notes',['../md_WORKLOG.html#autotoc_md200',1,'']]],
  ['scenario_3a_20add_20a_20new_20math_20function_1',['Scenario: Add a New Math Function',['../md_WORKLOG.html#autotoc_md168',1,'']]],
  ['se_20subió_2',['Paso 3: Verificar que se Subió',['../md_GITHUB__SETUP.html#autotoc_md97',1,'']]],
  ['seguridad_20y_20permisos_3',['Seguridad y permisos',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md89',1,'']]],
  ['setup_4',['Setup',['../md_WORKLOG.html#autotoc_md162',1,'']]],
  ['shift_20b_20tt_5',['Tasks (&lt;tt&gt;Ctrl+Shift+B&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md184',1,'']]],
  ['si_20algo_20falla_6',['Si Algo Falla',['../md_GITHUB__SETUP.html#autotoc_md107',1,'']]],
  ['si_20es_20par_7',['Ejercicio 6: Función que Comprueba si es Par',['../md_EXERCISES__BEGINNER.html#autotoc_md44',1,'']]],
  ['si_20falla_20con_20https_8',['Alternativa: Token de Acceso (si falla con HTTPS)',['../md_GITHUB__SETUP.html#autotoc_md103',1,'']]],
  ['simple_9',['simple',['../md_EXERCISES__BEGINNER.html#autotoc_md34',1,'Ejercicio 1: Función de Suma Simple'],['../md_EXERCISES__ADVANCED.html#autotoc_md19',1,'Ejercicio 6: Árbol Binario Simple']]],
  ['simple_20b_20tree_10',['Proyecto 8: Base de Datos Simple (B-Tree)',['../md_PROJECTS.html#autotoc_md132',1,'']]],
  ['simple_20vm_11',['Proyecto 9: Máquina Virtual Simple (VM)',['../md_PROJECTS.html#autotoc_md134',1,'']]],
  ['simulador_20de_20banco_12',['Proyecto 5: Simulador de Banco',['../md_PROJECTS.html#autotoc_md125',1,'']]],
  ['sistema_20de_20gestión_20de_20estudiantes_13',['Proyecto 4: Sistema de Gestión de Estudiantes',['../md_PROJECTS.html#autotoc_md123',1,'']]],
  ['skew_20detected_20warning_14',['&quot;Clock skew detected&quot; warning',['../md_WORKLOG.html#autotoc_md173',1,'']]],
  ['sort_15',['Ejercicio 9: Bubble Sort',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md77',1,'']]],
  ['src_20math_5futils_20c_20tt_20tt_20include_20math_5futils_20h_20tt_16',['4. Reusable Code (&lt;tt&gt;src/math_utils.c&lt;/tt&gt; + &lt;tt&gt;include/math_utils.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md181',1,'']]],
  ['stack_17',['Ejercicio 4: Pila (Stack)',['../md_EXERCISES__ADVANCED.html#autotoc_md15',1,'']]],
  ['started_20step_20by_20step_18',['Getting Started (Step-by-Step)',['../md_WORKLOG.html#autotoc_md151',1,'']]],
  ['step_201_3a_20launch_20wsl_19',['Step 1: Launch WSL',['../md_WORKLOG.html#autotoc_md152',1,'']]],
  ['step_202_3a_20navigate_20to_20your_20project_20',['Step 2: Navigate to Your Project',['../md_WORKLOG.html#autotoc_md153',1,'']]],
  ['step_203_3a_20check_20available_20tools_21',['Step 3: Check Available Tools',['../md_WORKLOG.html#autotoc_md154',1,'']]],
  ['step_204_3a_20build_20the_20project_22',['Step 4: Build the Project',['../md_WORKLOG.html#autotoc_md155',1,'']]],
  ['step_205_3a_20run_20the_20program_23',['Step 5: Run the Program',['../md_WORKLOG.html#autotoc_md156',1,'']]],
  ['step_206_3a_20run_20tests_24',['Step 6: Run Tests',['../md_WORKLOG.html#autotoc_md157',1,'']]],
  ['step_207_3a_20clean_20build_20artifacts_20optional_25',['Step 7: Clean Build Artifacts (Optional)',['../md_WORKLOG.html#autotoc_md158',1,'']]],
  ['step_208_3a_20use_20git_20optional_26',['Step 8: Use Git (Optional)',['../md_WORKLOG.html#autotoc_md159',1,'']]],
  ['step_20by_20step_27',['Getting Started (Step-by-Step)',['../md_WORKLOG.html#autotoc_md151',1,'']]],
  ['steps_20you_20can_20take_28',['Next Steps You Can Take',['../md_WORKLOG.html#autotoc_md198',1,'']]],
  ['struct_29',['Ejercicio 5: Función con Struct',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md69',1,'']]],
  ['structure_30',['1. Project Structure',['../md_WORKLOG.html#autotoc_md178',1,'']]],
  ['subió_31',['Paso 3: Verificar que se Subió',['../md_GITHUB__SETUP.html#autotoc_md97',1,'']]],
  ['subir_20a_20github_32',['📤 Guía: Subir a GitHub',['../md_GITHUB__SETUP.html',1,'']]],
  ['suma_20simple_33',['Ejercicio 1: Función de Suma Simple',['../md_EXERCISES__BEGINNER.html#autotoc_md34',1,'']]],
  ['suma_20tres_20números_34',['Ejercicio 9: Función que Suma Tres Números',['../md_EXERCISES__BEGINNER.html#autotoc_md50',1,'']]],
  ['summary_35',['Project Summary',['../md_WORKLOG.html#autotoc_md149',1,'']]],
  ['system_20makefile_36',['2. Build System (Makefile)',['../md_WORKLOG.html#autotoc_md179',1,'']]]
];
