var searchData=
[
  ['cómo_20completar_0',['cómo completar',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md81',1,'Cómo Completar'],['../md_EXERCISES__ADVANCED.html#autotoc_md29',1,'Cómo Completar']]],
  ['cómo_20completar_20los_20ejercicios_1',['Cómo Completar Los Ejercicios',['../md_EXERCISES__BEGINNER.html#autotoc_md54',1,'']]],
  ['cómo_20trabajar_20con_20estos_20proyectos_2',['🎓 Cómo Trabajar con Estos Proyectos',['../md_PROJECTS.html#autotoc_md138',1,'']]],
  ['cómo_20usar_20ahora_3',['Cómo usar ahora',['../md_DOCS__CHANGELOG.html#autotoc_md3',1,'']]],
  ['c_20construcción_20real_4',['Proyectos de C - Construcción Real',['../md_PROJECTS.html',1,'']]],
  ['c_20nivel_20avanzado_5',['Ejercicios de C - Nivel Avanzado',['../md_EXERCISES__ADVANCED.html',1,'']]],
  ['c_20nivel_20intermedio_6',['Ejercicios de C - Nivel Intermedio',['../md_EXERCISES__INTERMEDIATE.html',1,'']]],
  ['c_20nivel_20principiante_7',['Ejercicios de C - Nivel Principiante',['../md_EXERCISES__BEGINNER.html',1,'']]],
  ['c_20tt_20tt_20include_20math_5futils_20h_20tt_8',['4. Reusable Code (&lt;tt&gt;src/math_utils.c&lt;/tt&gt; + &lt;tt&gt;include/math_utils.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md181',1,'']]],
  ['c_20workplace_9',['Cambios y registro de documentación — c-workplace',['../md_DOCS__CHANGELOG.html',1,'']]],
  ['c_20workspace_20c_20workplace_10',['C Workspace (c-workplace)',['../md_README.html',1,'']]],
  ['c_20workspace_20worklog_11',['C Workspace Worklog',['../md_WORKLOG.html',1,'']]],
  ['c_3a_20vs_20code_20remote_20wsl_20recommended_12',['Option C: VS Code Remote - WSL (Recommended)',['../md_WORKLOG.html#autotoc_md194',1,'']]],
  ['cada_20cambio_13',['Descripción detallada de cada cambio',['../md_DOCS__CHANGELOG.html#autotoc_md2',1,'']]],
  ['cada_20proyecto_3a_14',['Para Cada Proyecto:',['../md_PROJECTS.html#autotoc_md139',1,'']]],
  ['calcula_20el_20absoluto_15',['Ejercicio 5: Función que Calcula el Absoluto',['../md_EXERCISES__BEGINNER.html#autotoc_md42',1,'']]],
  ['calcula_20potencia_16',['Ejercicio 7: Función que Calcula Potencia',['../md_EXERCISES__BEGINNER.html#autotoc_md46',1,'']]],
  ['calculadora_20interactiva_17',['Proyecto 1: Calculadora Interactiva',['../md_PROJECTS.html#autotoc_md116',1,'']]],
  ['cambio_18',['Descripción detallada de cada cambio',['../md_DOCS__CHANGELOG.html#autotoc_md2',1,'']]],
  ['cambios_20y_20registro_20de_20documentación_20—_20c_20workplace_19',['Cambios y registro de documentación — c-workplace',['../md_DOCS__CHANGELOG.html',1,'']]],
  ['can_20take_20',['Next Steps You Can Take',['../md_WORKLOG.html#autotoc_md198',1,'']]],
  ['check_20available_20tools_21',['Step 3: Check Available Tools',['../md_WORKLOG.html#autotoc_md154',1,'']]],
  ['clean_20build_20artifacts_20optional_22',['Step 7: Clean Build Artifacts (Optional)',['../md_WORKLOG.html#autotoc_md158',1,'']]],
  ['clock_20skew_20detected_20warning_23',['&quot;Clock skew detected&quot; warning',['../md_WORKLOG.html#autotoc_md173',1,'']]],
  ['cmd_24',['Option A: From Windows PowerShell/CMD',['../md_WORKLOG.html#autotoc_md192',1,'']]],
  ['code_25',['code',['../md_WORKLOG.html#autotoc_md163',1,'Build from VS Code'],['../md_WORKLOG.html#autotoc_md164',1,'Debug from VS Code'],['../md_WORKLOG.html#autotoc_md165',1,'Terminal in VS Code']]],
  ['code_20extensions_20local_20wsl_26',['VS Code Extensions (Local + WSL)',['../md_WORKLOG.html#autotoc_md190',1,'']]],
  ['code_20integration_27',['6. VS Code Integration',['../md_WORKLOG.html#autotoc_md183',1,'']]],
  ['code_20remote_20wsl_20recommended_28',['code remote wsl recommended',['../md_WORKLOG.html#autotoc_md194',1,'Option C: VS Code Remote - WSL (Recommended)'],['../md_WORKLOG.html#autotoc_md161',1,'Using VS Code Remote - WSL (Recommended)']]],
  ['code_20tt_20src_20math_5futils_20c_20tt_20tt_20include_20math_5futils_20h_20tt_29',['4. Reusable Code (&lt;tt&gt;src/math_utils.c&lt;/tt&gt; + &lt;tt&gt;include/math_utils.h&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md181',1,'']]],
  ['cola_20queue_30',['Ejercicio 5: Cola (Queue)',['../md_EXERCISES__ADVANCED.html#autotoc_md17',1,'']]],
  ['comando_20rápido_20copiar_20y_20pegar_31',['Comando Rápido (Copiar y Pegar)',['../md_GITHUB__SETUP.html#autotoc_md101',1,'']]],
  ['comandos_20útiles_32',['Comandos Útiles',['../md_EXERCISES__BEGINNER.html#autotoc_md56',1,'']]],
  ['command_20not_20found_33',['command not found',['../md_WORKLOG.html#autotoc_md172',1,'&quot;gcc: command not found&quot;'],['../md_WORKLOG.html#autotoc_md171',1,'&quot;make: command not found&quot;']]],
  ['commands_20you_20have_20available_34',['Commands You Have Available',['../md_WORKLOG.html#autotoc_md204',1,'']]],
  ['commits_35',['Paso 4: Futuros Commits',['../md_GITHUB__SETUP.html#autotoc_md99',1,'']]],
  ['compilador_20minimalista_36',['Proyecto 7: Compilador Minimalista',['../md_PROJECTS.html#autotoc_md130',1,'']]],
  ['completar_37',['completar',['../md_EXERCISES__ADVANCED.html#autotoc_md29',1,'Cómo Completar'],['../md_EXERCISES__INTERMEDIATE.html#autotoc_md81',1,'Cómo Completar']]],
  ['completar_20los_20ejercicios_38',['Cómo Completar Los Ejercicios',['../md_EXERCISES__BEGINNER.html#autotoc_md54',1,'']]],
  ['comprueba_20si_20es_20par_39',['Ejercicio 6: Función que Comprueba si es Par',['../md_EXERCISES__BEGINNER.html#autotoc_md44',1,'']]],
  ['con_20estos_20proyectos_40',['🎓 Cómo Trabajar con Estos Proyectos',['../md_PROJECTS.html#autotoc_md138',1,'']]],
  ['con_20https_41',['Alternativa: Token de Acceso (si falla con HTTPS)',['../md_GITHUB__SETUP.html#autotoc_md103',1,'']]],
  ['con_20struct_42',['Ejercicio 5: Función con Struct',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md69',1,'']]],
  ['conectar_20repositorio_20local_20a_20github_43',['Paso 2: Conectar Repositorio Local a GitHub',['../md_GITHUB__SETUP.html#autotoc_md95',1,'']]],
  ['configuración_20de_20git_44',['Verificar Configuración de Git',['../md_GITHUB__SETUP.html#autotoc_md105',1,'']]],
  ['configurations_20tt_20f5_20tt_45',['Debug Configurations (&lt;tt&gt;F5&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md185',1,'']]],
  ['construcción_20real_46',['Proyectos de C - Construcción Real',['../md_PROJECTS.html',1,'']]],
  ['contactos_47',['Proyecto 2: Gestor de Contactos',['../md_PROJECTS.html#autotoc_md118',1,'']]],
  ['contar_20ocurrencias_48',['Ejercicio 4: Contar Ocurrencias',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md67',1,'']]],
  ['copiar_20y_20pegar_49',['Comando Rápido (Copiar y Pegar)',['../md_GITHUB__SETUP.html#autotoc_md101',1,'']]],
  ['crear_20repositorio_20en_20github_50',['Paso 1: Crear Repositorio en GitHub',['../md_GITHUB__SETUP.html#autotoc_md93',1,'']]],
  ['created_20modified_51',['Files Created/Modified',['../md_WORKLOG.html#autotoc_md202',1,'']]],
  ['ctrl_20shift_20b_20tt_52',['Tasks (&lt;tt&gt;Ctrl+Shift+B&lt;/tt&gt;)',['../md_WORKLOG.html#autotoc_md184',1,'']]],
  ['cuenta_20dígitos_53',['Ejercicio 4: Función que Cuenta Dígitos',['../md_EXERCISES__BEGINNER.html#autotoc_md40',1,'']]]
];
