var searchData=
[
  ['editor_20de_20texto_20minimalista_0',['Proyecto 3: Editor de Texto Minimalista',['../md_PROJECTS.html#autotoc_md120',1,'']]],
  ['ejemplo_1',['Workflow de ejemplo',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md87',1,'']]],
  ['ejercicio_2010_3a_20estadísticas_20de_20array_2',['Ejercicio 10: Estadísticas de Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md79',1,'']]],
  ['ejercicio_2010_3a_20función_20que_20invierte_20un_20número_3',['Ejercicio 10: Función que Invierte un Número',['../md_EXERCISES__BEGINNER.html#autotoc_md52',1,'']]],
  ['ejercicio_2010_3a_20problema_20n_20reinas_20backtracking_4',['Ejercicio 10: Problema N-Reinas (Backtracking)',['../md_EXERCISES__ADVANCED.html#autotoc_md27',1,'']]],
  ['ejercicio_201_3a_20arrays_20y_20bucles_5',['Ejercicio 1: Arrays y Bucles',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md61',1,'']]],
  ['ejercicio_201_3a_20función_20de_20suma_20simple_6',['Ejercicio 1: Función de Suma Simple',['../md_EXERCISES__BEGINNER.html#autotoc_md34',1,'']]],
  ['ejercicio_201_3a_20recursión_20factorial_7',['Ejercicio 1: Recursión - Factorial',['../md_EXERCISES__ADVANCED.html#autotoc_md9',1,'']]],
  ['ejercicio_202_3a_20encontrar_20el_20máximo_20en_20un_20array_8',['Ejercicio 2: Encontrar el Máximo en un Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md63',1,'']]],
  ['ejercicio_202_3a_20función_20de_20resta_9',['Ejercicio 2: Función de Resta',['../md_EXERCISES__BEGINNER.html#autotoc_md36',1,'']]],
  ['ejercicio_202_3a_20recursión_20fibonacci_10',['Ejercicio 2: Recursión - Fibonacci',['../md_EXERCISES__ADVANCED.html#autotoc_md11',1,'']]],
  ['ejercicio_203_3a_20función_20de_20multiplicación_11',['Ejercicio 3: Función de Multiplicación',['../md_EXERCISES__BEGINNER.html#autotoc_md38',1,'']]],
  ['ejercicio_203_3a_20invertir_20un_20array_12',['Ejercicio 3: Invertir un Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md65',1,'']]],
  ['ejercicio_203_3a_20nodo_20de_20lista_20enlazada_13',['Ejercicio 3: Nodo de Lista Enlazada',['../md_EXERCISES__ADVANCED.html#autotoc_md13',1,'']]],
  ['ejercicio_204_3a_20contar_20ocurrencias_14',['Ejercicio 4: Contar Ocurrencias',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md67',1,'']]],
  ['ejercicio_204_3a_20función_20que_20cuenta_20dígitos_15',['Ejercicio 4: Función que Cuenta Dígitos',['../md_EXERCISES__BEGINNER.html#autotoc_md40',1,'']]],
  ['ejercicio_204_3a_20pila_20stack_16',['Ejercicio 4: Pila (Stack)',['../md_EXERCISES__ADVANCED.html#autotoc_md15',1,'']]],
  ['ejercicio_205_3a_20cola_20queue_17',['Ejercicio 5: Cola (Queue)',['../md_EXERCISES__ADVANCED.html#autotoc_md17',1,'']]],
  ['ejercicio_205_3a_20función_20con_20struct_18',['Ejercicio 5: Función con Struct',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md69',1,'']]],
  ['ejercicio_205_3a_20función_20que_20calcula_20el_20absoluto_19',['Ejercicio 5: Función que Calcula el Absoluto',['../md_EXERCISES__BEGINNER.html#autotoc_md42',1,'']]],
  ['ejercicio_206_3a_20árbol_20binario_20simple_20',['Ejercicio 6: Árbol Binario Simple',['../md_EXERCISES__ADVANCED.html#autotoc_md19',1,'']]],
  ['ejercicio_206_3a_20duplicar_20array_21',['Ejercicio 6: Duplicar Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md71',1,'']]],
  ['ejercicio_206_3a_20función_20que_20comprueba_20si_20es_20par_22',['Ejercicio 6: Función que Comprueba si es Par',['../md_EXERCISES__BEGINNER.html#autotoc_md44',1,'']]],
  ['ejercicio_207_3a_20filtrar_20array_23',['Ejercicio 7: Filtrar Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md73',1,'']]],
  ['ejercicio_207_3a_20función_20que_20calcula_20potencia_24',['Ejercicio 7: Función que Calcula Potencia',['../md_EXERCISES__BEGINNER.html#autotoc_md46',1,'']]],
  ['ejercicio_207_3a_20quicksort_20recursivo_25',['Ejercicio 7: Quicksort Recursivo',['../md_EXERCISES__ADVANCED.html#autotoc_md21',1,'']]],
  ['ejercicio_208_3a_20búsqueda_20binaria_26',['Ejercicio 8: Búsqueda Binaria',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md75',1,'']]],
  ['ejercicio_208_3a_20función_20que_20encuentra_20el_20máximo_27',['Ejercicio 8: Función que Encuentra el Máximo',['../md_EXERCISES__BEGINNER.html#autotoc_md48',1,'']]],
  ['ejercicio_208_3a_20manejo_20de_20archivos_28',['Ejercicio 8: Manejo de Archivos',['../md_EXERCISES__ADVANCED.html#autotoc_md23',1,'']]],
  ['ejercicio_209_3a_20búsqueda_20en_20profundidad_20dfs_29',['Ejercicio 9: Búsqueda en Profundidad (DFS)',['../md_EXERCISES__ADVANCED.html#autotoc_md25',1,'']]],
  ['ejercicio_209_3a_20bubble_20sort_30',['Ejercicio 9: Bubble Sort',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md77',1,'']]],
  ['ejercicio_209_3a_20función_20que_20suma_20tres_20números_31',['Ejercicio 9: Función que Suma Tres Números',['../md_EXERCISES__BEGINNER.html#autotoc_md50',1,'']]],
  ['ejercicios_32',['Cómo Completar Los Ejercicios',['../md_EXERCISES__BEGINNER.html#autotoc_md54',1,'']]],
  ['ejercicios_20de_20c_20nivel_20avanzado_33',['Ejercicios de C - Nivel Avanzado',['../md_EXERCISES__ADVANCED.html',1,'']]],
  ['ejercicios_20de_20c_20nivel_20intermedio_34',['Ejercicios de C - Nivel Intermedio',['../md_EXERCISES__INTERMEDIATE.html',1,'']]],
  ['ejercicios_20de_20c_20nivel_20principiante_35',['Ejercicios de C - Nivel Principiante',['../md_EXERCISES__BEGINNER.html',1,'']]],
  ['el_20absoluto_36',['Ejercicio 5: Función que Calcula el Absoluto',['../md_EXERCISES__BEGINNER.html#autotoc_md42',1,'']]],
  ['el_20máximo_37',['Ejercicio 8: Función que Encuentra el Máximo',['../md_EXERCISES__BEGINNER.html#autotoc_md48',1,'']]],
  ['el_20máximo_20en_20un_20array_38',['Ejercicio 2: Encontrar el Máximo en un Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md63',1,'']]],
  ['en_20github_39',['en github',['../md_GITHUB__SETUP.html#autotoc_md93',1,'Paso 1: Crear Repositorio en GitHub'],['../md_GITHUB__SETUP.html#autotoc_md111',1,'Próximos Pasos en GitHub']]],
  ['en_20github_20pages_40',['GitHub Actions — Publicar documentación Doxygen en GitHub Pages',['../md_GITHUB__ACTIONS__GUIDE.html',1,'']]],
  ['en_20profundidad_20dfs_41',['Ejercicio 9: Búsqueda en Profundidad (DFS)',['../md_EXERCISES__ADVANCED.html#autotoc_md25',1,'']]],
  ['en_20un_20array_42',['Ejercicio 2: Encontrar el Máximo en un Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md63',1,'']]],
  ['encontrar_20el_20máximo_20en_20un_20array_43',['Ejercicio 2: Encontrar el Máximo en un Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md63',1,'']]],
  ['encuentra_20el_20máximo_44',['Ejercicio 8: Función que Encuentra el Máximo',['../md_EXERCISES__BEGINNER.html#autotoc_md48',1,'']]],
  ['enlazada_45',['Ejercicio 3: Nodo de Lista Enlazada',['../md_EXERCISES__ADVANCED.html#autotoc_md13',1,'']]],
  ['environment_46',['Tools &amp; Environment',['../md_WORKLOG.html#autotoc_md188',1,'']]],
  ['es_20par_47',['Ejercicio 6: Función que Comprueba si es Par',['../md_EXERCISES__BEGINNER.html#autotoc_md44',1,'']]],
  ['esperar_20después_20del_20push_48',['Qué esperar después del push',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md88',1,'']]],
  ['estadísticas_20de_20array_49',['Ejercicio 10: Estadísticas de Array',['../md_EXERCISES__INTERMEDIATE.html#autotoc_md79',1,'']]],
  ['estado_20actual_20de_20tu_20proyecto_50',['Estado Actual de tu Proyecto',['../md_GITHUB__SETUP.html#autotoc_md109',1,'']]],
  ['estos_20proyectos_51',['estos proyectos',['../md_PROJECTS.html#autotoc_md138',1,'🎓 Cómo Trabajar con Estos Proyectos'],['../md_PROJECTS.html#autotoc_md144',1,'🏆 Próximos Pasos Después de Estos Proyectos']]],
  ['estudiantes_52',['Proyecto 4: Sistema de Gestión de Estudiantes',['../md_PROJECTS.html#autotoc_md123',1,'']]],
  ['exercises_5fadvanced_2emd_53',['EXERCISES_ADVANCED.md',['../EXERCISES__ADVANCED_8md.html',1,'']]],
  ['exercises_5fbeginner_2emd_54',['EXERCISES_BEGINNER.md',['../EXERCISES__BEGINNER_8md.html',1,'']]],
  ['exercises_5fintermediate_2emd_55',['EXERCISES_INTERMEDIATE.md',['../EXERCISES__INTERMEDIATE_8md.html',1,'']]],
  ['extensions_56',['Recommended Extensions',['../md_WORKLOG.html#autotoc_md186',1,'']]],
  ['extensions_20local_20wsl_57',['VS Code Extensions (Local + WSL)',['../md_WORKLOG.html#autotoc_md190',1,'']]]
];
