var searchData=
[
  ['pages_0',['GitHub Actions — Publicar documentación Doxygen en GitHub Pages',['../md_GITHUB__ACTIONS__GUIDE.html',1,'']]],
  ['par_1',['Ejercicio 6: Función que Comprueba si es Par',['../md_EXERCISES__BEGINNER.html#autotoc_md84',1,'']]],
  ['para_20cada_20proyecto_3a_2',['Para Cada Proyecto:',['../md_PROJECTS.html#autotoc_md179',1,'']]],
  ['para_20empezar_3',['Minimalista (para empezar)',['../md_CPP__STACK.html#autotoc_md36',1,'']]],
  ['paso_4',['paso',['../md_EXERCISES__BEGINNER.html#autotoc_md98',1,'Próximo Paso'],['../md_EXERCISES__INTERMEDIATE.html#autotoc_md123',1,'Próximo Paso']]],
  ['paso_201_3a_20crear_20repositorio_20en_20github_5',['Paso 1: Crear Repositorio en GitHub',['../md_GITHUB__SETUP.html#autotoc_md133',1,'']]],
  ['paso_202_3a_20conectar_20repositorio_20local_20a_20github_6',['Paso 2: Conectar Repositorio Local a GitHub',['../md_GITHUB__SETUP.html#autotoc_md135',1,'']]],
  ['paso_203_3a_20verificar_20que_20se_20subió_7',['Paso 3: Verificar que se Subió',['../md_GITHUB__SETUP.html#autotoc_md137',1,'']]],
  ['paso_204_3a_20futuros_20commits_8',['Paso 4: Futuros Commits',['../md_GITHUB__SETUP.html#autotoc_md139',1,'']]],
  ['pasos_9',['pasos',['../md_EXERCISES__ADVANCED.html#autotoc_md71',1,'Próximos Pasos'],['../md_CPP__STACK.html#autotoc_md38',1,'Siguientes pasos']]],
  ['pasos_20después_20de_20estos_20proyectos_10',['🏆 Próximos Pasos Después de Estos Proyectos',['../md_PROJECTS.html#autotoc_md184',1,'']]],
  ['pasos_20en_20github_11',['Próximos Pasos en GitHub',['../md_GITHUB__SETUP.html#autotoc_md151',1,'']]],
  ['pegar_12',['Comando Rápido (Copiar y Pegar)',['../md_GITHUB__SETUP.html#autotoc_md141',1,'']]],
  ['permisos_13',['Seguridad y permisos',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md129',1,'']]],
  ['permission_20denied_20when_20running_20tt_20build_20main_20tt_14',['&quot;Permission denied&quot; when running &lt;tt&gt;build/main&lt;/tt&gt;',['../md_WORKLOG.html#autotoc_md215',1,'']]],
  ['pila_20stack_15',['Ejercicio 4: Pila (Stack)',['../md_EXERCISES__ADVANCED.html#autotoc_md55',1,'']]],
  ['populares_16',['Librerías externas populares',['../md_CPP__STACK.html#autotoc_md19',1,'']]],
  ['potencia_17',['Ejercicio 7: Función que Calcula Potencia',['../md_EXERCISES__BEGINNER.html#autotoc_md86',1,'']]],
  ['powershell_20cmd_18',['Option A: From Windows PowerShell/CMD',['../md_WORKLOG.html#autotoc_md232',1,'']]],
  ['próximo_20paso_19',['próximo paso',['../md_EXERCISES__BEGINNER.html#autotoc_md98',1,'Próximo Paso'],['../md_EXERCISES__INTERMEDIATE.html#autotoc_md123',1,'Próximo Paso']]],
  ['próximos_20pasos_20',['Próximos Pasos',['../md_EXERCISES__ADVANCED.html#autotoc_md71',1,'']]],
  ['próximos_20pasos_20después_20de_20estos_20proyectos_21',['🏆 Próximos Pasos Después de Estos Proyectos',['../md_PROJECTS.html#autotoc_md184',1,'']]],
  ['próximos_20pasos_20en_20github_22',['Próximos Pasos en GitHub',['../md_GITHUB__SETUP.html#autotoc_md151',1,'']]],
  ['principiante_23',['principiante',['../md_PROJECTS.html#autotoc_md155',1,'🔰 NIVEL PRINCIPIANTE'],['../md_EXERCISES__BEGINNER.html',1,'Ejercicios de C - Nivel Principiante']]],
  ['problema_20n_20reinas_20backtracking_24',['Ejercicio 10: Problema N-Reinas (Backtracking)',['../md_EXERCISES__ADVANCED.html#autotoc_md67',1,'']]],
  ['profesional_25',['profesional',['../md_CPP__STACK.html#autotoc_md9',1,'CMake (profesional)'],['../md_CPP__STACK.html#autotoc_md35',1,'Stack minimalista vs profesional']]],
  ['profesional_20empresarial_26',['Profesional (empresarial)',['../md_CPP__STACK.html#autotoc_md37',1,'']]],
  ['profesionales_27',['C/C++ Development Stack — Herramientas, librerías y extensiones profesionales',['../md_CPP__STACK.html',1,'']]],
  ['profundidad_20dfs_28',['Ejercicio 9: Búsqueda en Profundidad (DFS)',['../md_EXERCISES__ADVANCED.html#autotoc_md65',1,'']]],
  ['program_29',['Step 5: Run the Program',['../md_WORKLOG.html#autotoc_md196',1,'']]],
  ['project_30',['project',['../md_WORKLOG.html#autotoc_md193',1,'Step 2: Navigate to Your Project'],['../md_WORKLOG.html#autotoc_md195',1,'Step 4: Build the Project']]],
  ['project_20structure_31',['1. Project Structure',['../md_WORKLOG.html#autotoc_md218',1,'']]],
  ['project_20summary_32',['Project Summary',['../md_WORKLOG.html#autotoc_md189',1,'']]],
  ['projects_2emd_33',['PROJECTS.md',['../PROJECTS_8md.html',1,'']]],
  ['proyecto_34',['Estado Actual de tu Proyecto',['../md_GITHUB__SETUP.html#autotoc_md149',1,'']]],
  ['proyecto_201_3a_20calculadora_20interactiva_35',['Proyecto 1: Calculadora Interactiva',['../md_PROJECTS.html#autotoc_md156',1,'']]],
  ['proyecto_202_3a_20gestor_20de_20contactos_36',['Proyecto 2: Gestor de Contactos',['../md_PROJECTS.html#autotoc_md158',1,'']]],
  ['proyecto_203_3a_20editor_20de_20texto_20minimalista_37',['Proyecto 3: Editor de Texto Minimalista',['../md_PROJECTS.html#autotoc_md160',1,'']]],
  ['proyecto_204_3a_20sistema_20de_20gestión_20de_20estudiantes_38',['Proyecto 4: Sistema de Gestión de Estudiantes',['../md_PROJECTS.html#autotoc_md163',1,'']]],
  ['proyecto_205_3a_20simulador_20de_20banco_39',['Proyecto 5: Simulador de Banco',['../md_PROJECTS.html#autotoc_md165',1,'']]],
  ['proyecto_206_3a_20analizador_20de_20logs_40',['Proyecto 6: Analizador de Logs',['../md_PROJECTS.html#autotoc_md167',1,'']]],
  ['proyecto_207_3a_20compilador_20minimalista_41',['Proyecto 7: Compilador Minimalista',['../md_PROJECTS.html#autotoc_md170',1,'']]],
  ['proyecto_208_3a_20base_20de_20datos_20simple_20b_20tree_42',['Proyecto 8: Base de Datos Simple (B-Tree)',['../md_PROJECTS.html#autotoc_md172',1,'']]],
  ['proyecto_209_3a_20máquina_20virtual_20simple_20vm_43',['Proyecto 9: Máquina Virtual Simple (VM)',['../md_PROJECTS.html#autotoc_md174',1,'']]],
  ['proyecto_3a_44',['Para Cada Proyecto:',['../md_PROJECTS.html#autotoc_md179',1,'']]],
  ['proyectos_45',['proyectos',['../md_PROJECTS.html#autotoc_md178',1,'🎓 Cómo Trabajar con Estos Proyectos'],['../md_PROJECTS.html#autotoc_md184',1,'🏆 Próximos Pasos Después de Estos Proyectos']]],
  ['proyectos_20de_20c_20construcción_20real_46',['Proyectos de C - Construcción Real',['../md_PROJECTS.html',1,'']]],
  ['publicar_20documentación_20doxygen_20en_20github_20pages_47',['GitHub Actions — Publicar documentación Doxygen en GitHub Pages',['../md_GITHUB__ACTIONS__GUIDE.html',1,'']]],
  ['push_48',['Qué esperar después del push',['../md_GITHUB__ACTIONS__GUIDE.html#autotoc_md128',1,'']]]
];
