var searchData=
[
  ['gcc_20gnu_20compiler_20collection_0',['GCC (GNU Compiler Collection)',['../md_CPP__STACK.html#autotoc_md4',1,'']]],
  ['gcc_3a_20command_20not_20found_1',['&quot;gcc: command not found&quot;',['../md_WORKLOG.html#autotoc_md212',1,'']]],
  ['gdb_20gnu_20debugger_2',['GDB (GNU Debugger)',['../md_CPP__STACK.html#autotoc_md21',1,'']]],
  ['gestión_20de_20estudiantes_3',['Proyecto 4: Sistema de Gestión de Estudiantes',['../md_PROJECTS.html#autotoc_md163',1,'']]],
  ['gestor_20de_20contactos_4',['Proyecto 2: Gestor de Contactos',['../md_PROJECTS.html#autotoc_md158',1,'']]],
  ['getting_20started_20step_20by_20step_5',['Getting Started (Step-by-Step)',['../md_WORKLOG.html#autotoc_md191',1,'']]],
  ['git_6',['Verificar Configuración de Git',['../md_GITHUB__SETUP.html#autotoc_md145',1,'']]],
  ['git_20cli_20guide_7',['Git CLI Guide',['../git_cli_guide.html',1,'']]],
  ['git_20optional_8',['Step 8: Use Git (Optional)',['../md_WORKLOG.html#autotoc_md199',1,'']]],
  ['git_20repository_9',['5. Git Repository',['../md_WORKLOG.html#autotoc_md222',1,'']]],
  ['github_10',['github',['../md_GITHUB__SETUP.html',1,'📤 Guía: Subir a GitHub'],['../md_GITHUB__SETUP.html#autotoc_md133',1,'Paso 1: Crear Repositorio en GitHub'],['../md_GITHUB__SETUP.html#autotoc_md135',1,'Paso 2: Conectar Repositorio Local a GitHub'],['../md_GITHUB__SETUP.html#autotoc_md151',1,'Próximos Pasos en GitHub']]],
  ['github_20actions_20—_20publicar_20documentación_20doxygen_20en_20github_20pages_11',['GitHub Actions — Publicar documentación Doxygen en GitHub Pages',['../md_GITHUB__ACTIONS__GUIDE.html',1,'']]],
  ['github_20actions_20guide_12',['GitHub Actions Guide',['../github_actions_guide.html',1,'']]],
  ['github_20actions_20workflow_13',['GitHub Actions workflow',['../md_CPP__STACK.html#autotoc_md34',1,'']]],
  ['github_5factions_5fguide_2emd_14',['GITHUB_ACTIONS_GUIDE.md',['../GITHUB__ACTIONS__GUIDE_8md.html',1,'']]],
  ['github_5fsetup_2emd_15',['GITHUB_SETUP.md',['../GITHUB__SETUP_8md.html',1,'']]],
  ['gnu_20compiler_20collection_16',['GCC (GNU Compiler Collection)',['../md_CPP__STACK.html#autotoc_md4',1,'']]],
  ['gnu_20debugger_17',['GDB (GNU Debugger)',['../md_CPP__STACK.html#autotoc_md21',1,'']]],
  ['googletest_20c_20o_20c_20con_20wrapper_18',['GoogleTest (C++ o C con wrapper)',['../md_CPP__STACK.html#autotoc_md15',1,'']]],
  ['guía_3a_20subir_20a_20github_19',['📤 Guía: Subir a GitHub',['../md_GITHUB__SETUP.html',1,'']]],
  ['guías_20útiles_20',['guías útiles',['../index.html#autotoc_md187',1,'Guías útiles'],['..//home/runner/work/c-workplace/c-workplace/pages.dox#autotoc_md247',1,'Guías útiles']]],
  ['guide_21',['guide',['../git_cli_guide.html',1,'Git CLI Guide'],['../github_actions_guide.html',1,'GitHub Actions Guide']]]
];
